// generated by `dankg tangle` from src/tui/input.md -- do not edit

//! Raw bytes off stdin, decoded into key events.
//!
//! Split in two on purpose. [`decode`] is a pure function over an
//! already-collected byte slice and is fully unit-testable without a
//! terminal, unlike everything in [`crate::tui::term`]. [`read_key`] is the
//! thin, untested I/O wrapper that feeds it one byte at a time from a real
//! reader.

use std::io::{self, Read};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Key {
    Char(char),
    /// A control byte with no more specific meaning below, as the letter it
    /// pairs with: Ctrl-C is `Ctrl('c')`.
    Ctrl(char),
    Enter,
    Tab,
    Backspace,
    Esc,
    Up,
    Down,
    Left,
    Right,
}

/// Decodes the key event at the front of `bytes`, returning it along
/// with how many bytes it consumed. This can be *fewer* than
/// `bytes.len()`: a lone `ESC` cannot be told apart from the start of
/// `ESC [ <letter>` without reading one more byte, and when that byte
/// turns out not to be `[`, it was never part of the Esc and is
/// reported as unused, rather than swallowed. [`read_key`] carries
/// that unused byte forward into the next call, rather than discarding
/// it. That is what makes it safe to bind Esc to something (`app.rs`
/// does, to cancel an eval cycle or dismiss help) without silently
/// eating whatever key the reader pressed right after it.
///
/// `None` means `bytes` is a prefix of a longer sequence. `decode`
/// itself has no sense of time. It cannot tell "the rest of the
/// sequence is still in flight" apart from "there is no rest of the
/// sequence coming." [`read_key`] is what actually waits. Only it
/// knows how long is too long.
pub fn decode(bytes: &[u8]) -> Option<(Key, usize)> {
    let &first = bytes.first()?;
    match first {
        0x1b => {
            if bytes.len() < 2 {
                return None;
            }
            if bytes[1] != b'[' {
                return Some((Key::Esc, 1));
            }
            if bytes.len() < 3 {
                return None;
            }
            let key = match bytes[2] {
                b'A' => Key::Up,
                b'B' => Key::Down,
                b'C' => Key::Right,
                b'D' => Key::Left,
                _ => return Some((Key::Esc, 1)),
            };
            Some((key, 3))
        }
        b'\r' | b'\n' => Some((Key::Enter, 1)),
        b'\t' => Some((Key::Tab, 1)),
        0x7f | 0x08 => Some((Key::Backspace, 1)),
        0x01..=0x1a => Some((Key::Ctrl((first - 1 + b'a') as char), 1)),
        _ => {
            let width = utf8_width(first);
            if bytes.len() < width {
                return None;
            }
            let ch = std::str::from_utf8(&bytes[..width]).ok()?.chars().next()?;
            Some((Key::Char(ch), width))
        }
    }
}

/// Parses a `key=` attribute's value (`[tui] commands`) into the `Key`
/// it names: a single character (`g`), `ctrl+` followed by one
/// (`ctrl+g`), or one of the named keys `decode` itself can produce
/// (`enter`, `tab`, `backspace`, `esc`, `up`, `down`, `left`, `right`),
/// matched case-insensitively. `ctrl+`'s own letter is always
/// lowercased, since `decode` never reports an uppercase `Ctrl` either
/// -- a real terminal cannot tell Ctrl-G from Ctrl-g apart. Anything
/// else -- more than one character, an empty string, an unrecognised
/// word -- is not a `Key` at all.
pub fn parse(raw: &str) -> Option<Key> {
    let raw = raw.trim();
    let mut chars = raw.chars();
    if let (Some(c), None) = (chars.next(), chars.next()) {
        return Some(Key::Char(c));
    }
    let lower = raw.to_ascii_lowercase();
    if let Some(rest) = lower.strip_prefix("ctrl+") {
        let mut rest_chars = rest.chars();
        return match (rest_chars.next(), rest_chars.next()) {
            (Some(c), None) => Some(Key::Ctrl(c)),
            _ => None,
        };
    }
    match lower.as_str() {
        "enter" => Some(Key::Enter),
        "tab" => Some(Key::Tab),
        "backspace" => Some(Key::Backspace),
        "esc" | "escape" => Some(Key::Esc),
        "up" => Some(Key::Up),
        "down" => Some(Key::Down),
        "left" => Some(Key::Left),
        "right" => Some(Key::Right),
        _ => None,
    }
}

/// The exact text `parse` accepts back: `Key::Char('g')` is `g`,
/// `Key::Ctrl('g')` is `ctrl+g`, and every other variant is its own
/// lowercase name (`enter`, `tab`, `esc`, `up`, ...). `parse(&key.to_string())
/// == Some(key)` for every `Key`, so this is also what a help screen or a
/// collision warning shows a reader, rather than `Key`'s own `Debug` form.
impl std::fmt::Display for Key {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Key::Char(c) => write!(f, "{c}"),
            Key::Ctrl(c) => write!(f, "ctrl+{c}"),
            Key::Enter => write!(f, "enter"),
            Key::Tab => write!(f, "tab"),
            Key::Backspace => write!(f, "backspace"),
            Key::Esc => write!(f, "esc"),
            Key::Up => write!(f, "up"),
            Key::Down => write!(f, "down"),
            Key::Left => write!(f, "left"),
            Key::Right => write!(f, "right"),
        }
    }
}

/// Bytes in the UTF-8 sequence starting with `first`. An invalid leading
/// byte is treated as width 1 so decoding cannot stall waiting for bytes
/// that were never going to complete a scalar.
fn utf8_width(first: u8) -> usize {
    if first & 0x80 == 0 {
        1
    } else if first & 0xe0 == 0xc0 {
        2
    } else if first & 0xf0 == 0xe0 {
        3
    } else if first & 0xf8 == 0xf0 {
        4
    } else {
        1
    }
}

/// How long `read_key` gives a lone `ESC` to turn into `ESC [
/// <letter>` before deciding nothing more is coming. A real terminal
/// sends the rest of an escape sequence essentially at once. This
/// only ever adds latency to an Esc the reader actually pressed alone.
const ESC_TIMEOUT_MS: i32 = 50;

/// Blocks until one key event is available on `r`, threading
/// `pending` across calls for exactly one reason: a standalone Esc is
/// only disambiguated from the start of `ESC [ <letter>` by reading
/// one byte past it (see [`decode`]'s doc comment), and when that byte
/// turns out not to be `[`, `decode` reports it as unused
/// (`Some((Key::Esc, 1))` from a two-byte buffer) rather than silently
/// absorbing it into the Esc. That leftover byte is the start of the
/// *next* key the reader actually typed. Dropping it, which a fresh,
/// unshared buffer on every call would do, would either fail the
/// `used == buf.len()` assumption below or, worse, eat whatever they
/// pressed right after Esc. The caller owns `pending` (an empty `Vec`
/// to start) purely so it survives between calls. Nothing about its
/// contents matters to the caller otherwise.
///
/// `esc_ready` is asked exactly one question, only when `buf` is a
/// lone, unresolved `0x1b`: "is a second byte likely within
/// `ESC_TIMEOUT_MS`?" A `false` answer means the reader pressed Esc by
/// itself. `read_key` then reports it immediately, rather than
/// blocking on `r` for a follow-up byte that a plain keypress was
/// never going to send. In production this is `term::stdin_ready`.
/// Tests pass a fixed answer instead of polling a real terminal.
pub fn read_key<R: Read>(mut r: R, pending: &mut Vec<u8>, esc_ready: impl Fn(i32) -> bool) -> io::Result<Key> {
    let mut buf = std::mem::take(pending);
    loop {
        if let Some((key, used)) = decode(&buf) {
            *pending = buf.split_off(used);
            return Ok(key);
        }
        if buf == [0x1b] && !esc_ready(ESC_TIMEOUT_MS) {
            return Ok(Key::Esc);
        }
        let mut byte = [0u8; 1];
        if r.read(&mut byte)? == 0 {
            return Err(io::Error::new(io::ErrorKind::UnexpectedEof, "stdin closed"));
        }
        buf.push(byte[0]);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plain_ascii_and_control_chars() {
        assert_eq!(decode(b"q"), Some((Key::Char('q'), 1)));
        assert_eq!(decode(b"\r"), Some((Key::Enter, 1)));
        assert_eq!(decode(b"\n"), Some((Key::Enter, 1)));
        assert_eq!(decode(b"\t"), Some((Key::Tab, 1)));
        assert_eq!(decode(&[0x7f]), Some((Key::Backspace, 1)));
        assert_eq!(decode(&[0x03]), Some((Key::Ctrl('c'), 1))); // as seen from the real terminal
    }

    #[test]
    fn arrow_keys_are_three_byte_sequences() {
        assert_eq!(decode(b"\x1b[A"), Some((Key::Up, 3)));
        assert_eq!(decode(b"\x1b[B"), Some((Key::Down, 3)));
        assert_eq!(decode(b"\x1b[C"), Some((Key::Right, 3)));
        assert_eq!(decode(b"\x1b[D"), Some((Key::Left, 3)));
    }

    #[test]
    fn a_lone_or_incomplete_escape_asks_for_more_bytes() {
        assert_eq!(decode(b"\x1b"), None);
        assert_eq!(decode(b"\x1b["), None);
    }

    #[test]
    fn an_unrecognised_escape_sequence_falls_back_to_a_standalone_esc() {
        assert_eq!(decode(b"\x1bZ"), Some((Key::Esc, 1)));
        assert_eq!(decode(b"\x1b[Z"), Some((Key::Esc, 1)));
    }

    #[test]
    fn multibyte_utf8_is_one_key_not_several() {
        // 'é' = U+00E9, 2 bytes.
        let bytes = "é".as_bytes();
        assert_eq!(decode(bytes), Some((Key::Char('é'), 2)));
        // A truncated scalar asks for more rather than misdecoding.
        assert_eq!(decode(&bytes[..1]), None);
    }

    #[test]
    fn read_key_assembles_bytes_from_a_reader() {
        let mut src: &[u8] = b"\x1b[A";
        let mut pending = Vec::new();
        // `esc_ready` says "yes, more is coming" -- there really is.
        // This reads straight through to the full sequence.
        assert_eq!(read_key(&mut src, &mut pending, |_| true).unwrap(), Key::Up);
        assert!(pending.is_empty(), "a fully-used sequence leaves nothing pending");
    }

    #[test]
    fn read_key_does_not_lose_the_byte_after_a_standalone_esc() {
        // A real standalone Esc keypress followed immediately by
        // another key ('q' here) arrives as one contiguous read. decode
        // reports the Esc as using only 1 of the 2 bytes it had to look
        // at, and that second byte must come back out of the *next*
        // read_key call, rather than being silently dropped.
        let mut src: &[u8] = b"\x1bq";
        let mut pending = Vec::new();
        assert_eq!(read_key(&mut src, &mut pending, |_| true).unwrap(), Key::Esc);
        assert_eq!(pending, vec![b'q'], "'q' was read but not yet consumed by decode");
        assert_eq!(read_key(&mut src, &mut pending, |_| true).unwrap(), Key::Char('q'));
        assert!(pending.is_empty());
    }

    #[test]
    fn read_key_reports_a_standalone_esc_without_blocking_on_more_input() {
        // Nothing follows the Esc in `src` at all. If `read_key` tried
        // to block-read a second byte here regardless of `esc_ready`,
        // it would hit EOF on the empty remainder and return an error
        // instead of `Key::Esc` -- this is what proves it did not try.
        let mut src: &[u8] = b"\x1b";
        let mut pending = Vec::new();
        assert_eq!(read_key(&mut src, &mut pending, |_| false).unwrap(), Key::Esc);
        assert!(pending.is_empty(), "a standalone Esc used its one byte outright");
    }

    #[test]
    fn read_key_still_waits_out_a_slow_but_real_escape_sequence() {
        // `esc_ready` says yes. A lone `0x1b` alone is not enough to
        // report Esc -- read_key keeps reading until `decode` actually
        // resolves it, exactly as it always has.
        let mut src: &[u8] = b"\x1b[D";
        let mut pending = Vec::new();
        assert_eq!(read_key(&mut src, &mut pending, |_| true).unwrap(), Key::Left);
    }

    #[test]
    fn parse_reads_a_single_character() {
        assert_eq!(parse("g"), Some(Key::Char('g')));
        assert_eq!(parse("G"), Some(Key::Char('G')), "shift is a distinct char, not lowercased");
    }

    #[test]
    fn parse_reads_ctrl_combinations_case_insensitively_and_lowercases_the_letter() {
        assert_eq!(parse("ctrl+g"), Some(Key::Ctrl('g')));
        assert_eq!(parse("Ctrl+G"), Some(Key::Ctrl('g')), "a real terminal cannot tell Ctrl-G from Ctrl-g apart");
    }

    #[test]
    fn parse_reads_named_keys_case_insensitively() {
        assert_eq!(parse("Enter"), Some(Key::Enter));
        assert_eq!(parse("tab"), Some(Key::Tab));
        assert_eq!(parse("BACKSPACE"), Some(Key::Backspace));
        assert_eq!(parse("esc"), Some(Key::Esc));
        assert_eq!(parse("escape"), Some(Key::Esc));
        assert_eq!(parse("Up"), Some(Key::Up));
        assert_eq!(parse("down"), Some(Key::Down));
        assert_eq!(parse("left"), Some(Key::Left));
        assert_eq!(parse("right"), Some(Key::Right));
    }

    #[test]
    fn parse_rejects_empty_multi_word_and_unknown_input() {
        assert_eq!(parse(""), None);
        assert_eq!(parse("ctrl+"), None);
        assert_eq!(parse("ctrl+gg"), None);
        assert_eq!(parse("pageup"), None);
    }

    #[test]
    fn display_round_trips_through_parse_for_every_variant() {
        let keys = [
            Key::Char('g'),
            Key::Char('G'),
            Key::Ctrl('g'),
            Key::Enter,
            Key::Tab,
            Key::Backspace,
            Key::Esc,
            Key::Up,
            Key::Down,
            Key::Left,
            Key::Right,
        ];
        for key in keys {
            assert_eq!(parse(&key.to_string()), Some(key), "{key} did not round-trip");
        }
    }

    #[test]
    fn read_key_replays_pending_bytes_without_reading_again_if_they_already_decode() {
        // If `pending` alone already decodes to a full key, read_key
        // must not block trying to read more from `r`. An empty reader
        // here would hang forever if it did.
        let mut empty: &[u8] = b"";
        let mut pending = vec![b'q'];
        assert_eq!(read_key(&mut empty, &mut pending, |_| true).unwrap(), Key::Char('q'));
    }
}
