// generated by `dankg tangle` from src/graph/query.md -- do not edit

//! Read-only lookups over an already-built `Graph`.

use super::build::relation_node;
use super::model::{EdgeKind, Graph, Node, NodeId, NodeKind};

/// Resolves `relation_name` against `graph`'s own `Produces` edges,
/// searching every `Relation` node whose slug matches it regardless of
/// which `db:*` namespace it lives in. Exactly one producing block
/// resolves; zero or more than one refuses, decision 35's own rule.
pub fn find_producer(graph: &Graph, relation_name: &str) -> Result<NodeId, String> {
    let candidates: Vec<&NodeId> = graph
        .nodes
        .iter()
        .filter(|n| n.kind == NodeKind::Relation && n.id.slug == relation_name)
        .flat_map(|relation| {
            graph
                .edges
                .iter()
                .filter(move |e| e.kind == EdgeKind::Produces && e.to == relation.id)
                .map(|e| &e.from)
        })
        .collect();

    match candidates.as_slice() {
        [one] => Ok((*one).clone()),
        [] => Err(format!("no block produces a relation named `{relation_name}`")),
        many => Err(format!(
            "`{relation_name}` is ambiguous: {} blocks produce a relation by that name ({})",
            many.len(),
            many.iter().map(|id| id.to_string()).collect::<Vec<_>>().join(", ")
        )),
    }
}

/// Relation names `db_name`'s configured `list` command reported that
/// `graph` has no node for at all -- a table created by hand, by a tool
/// `dankg` never touched, or documented once by a section since deleted.
/// Duplicates within `relations` collapse to one node, the same as two
/// files naming the same relation already do at build time.
pub fn live_orphans(graph: &Graph, db_name: &str, relations: &[String]) -> Vec<Node> {
    let db_ns = format!("db:{db_name}");
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for name in relations {
        let id = NodeId::new(&db_ns, name.as_str());
        if graph.contains(&id) || !seen.insert(id.clone()) {
            continue;
        }
        out.push(relation_node(&id, name));
    }
    out
}

/// Every `Link`/`Produces`/`Reads` edge touching `id`, partitioned by
/// kind and by which side `id` is on.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct NodeLinks {
    /// `Link` edges `id` is the `from` of: `id -> outgoing[i]`.
    pub outgoing: Vec<NodeId>,
    /// `Link` edges `id` is the `to` of: `backlinks[i] -> id`.
    pub backlinks: Vec<NodeId>,
    /// `Produces` edges `id` is the `from` of: relations `id` writes.
    pub produces: Vec<NodeId>,
    /// `Reads` edges `id` is the `to` of: relations `id` reads.
    pub reads: Vec<NodeId>,
}

pub fn links_for(graph: &Graph, id: &NodeId) -> NodeLinks {
    let mut out = NodeLinks::default();
    for edge in &graph.edges {
        match edge.kind {
            EdgeKind::Link if edge.from == *id => out.outgoing.push(edge.to.clone()),
            EdgeKind::Link if edge.to == *id => out.backlinks.push(edge.from.clone()),
            EdgeKind::Produces if edge.from == *id => out.produces.push(edge.to.clone()),
            EdgeKind::Reads if edge.to == *id => out.reads.push(edge.from.clone()),
            _ => {}
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use super::super::model::{Edge, Node};

    fn relation(db: &str, name: &str) -> Node {
        Node {
            id: NodeId::new(format!("db:{db}"), name),
            title: name.to_string(),
            file: format!("db:{db}"),
            line: 0,
            end_line: 0,
            level: 7,
            parent: None,
            tags: Vec::new(),
            external: Vec::new(),
            resolved: true,
            kind: NodeKind::Relation,
        }
    }

    fn produces(block: (&str, &str), relation: &NodeId) -> Edge {
        Edge {
            from: NodeId::new(block.0, block.1),
            to: relation.clone(),
            kind: EdgeKind::Produces,
            line: 0,
            reciprocated: false,
        }
    }

    #[test]
    fn exactly_one_producer_resolves() {
        let rel = relation("warehouse", "orders");
        let g = Graph { nodes: vec![rel.clone()], edges: vec![produces(("a", "setup"), &rel.id)] };
        assert_eq!(find_producer(&g, "orders").unwrap(), NodeId::new("a", "setup"));
    }

    #[test]
    fn no_producer_refuses() {
        let g = Graph { nodes: vec![relation("warehouse", "orders")], edges: vec![] };
        let err = find_producer(&g, "orders").unwrap_err();
        assert!(err.contains("no block produces"), "{err:?}");
    }

    #[test]
    fn an_unknown_relation_name_refuses_the_same_way() {
        let g = Graph { nodes: vec![], edges: vec![] };
        let err = find_producer(&g, "ghost").unwrap_err();
        assert!(err.contains("no block produces"), "{err:?}");
    }

    #[test]
    fn two_producers_in_different_databases_refuses_as_ambiguous() {
        let rel_a = relation("warehouse", "orders");
        let rel_b = relation("staging", "orders");
        let g = Graph {
            nodes: vec![rel_a.clone(), rel_b.clone()],
            edges: vec![produces(("a", "setup"), &rel_a.id), produces(("b", "other"), &rel_b.id)],
        };
        let err = find_producer(&g, "orders").unwrap_err();
        assert!(err.contains("ambiguous"), "{err:?}");
    }

    #[test]
    fn two_blocks_producing_the_same_relation_node_refuses_as_ambiguous() {
        // A relation a later block drops and recreates, decision 35's own
        // second example of the ambiguous case -- still just "more than
        // one candidate", not a different kind of error.
        let rel = relation("warehouse", "orders");
        let g = Graph {
            nodes: vec![rel.clone()],
            edges: vec![produces(("a", "setup"), &rel.id), produces(("a", "rebuild"), &rel.id)],
        };
        let err = find_producer(&g, "orders").unwrap_err();
        assert!(err.contains("ambiguous"), "{err:?}");
    }

    #[test]
    fn live_orphans_returns_a_node_for_a_name_the_graph_does_not_have() {
        let g = Graph { nodes: vec![], edges: vec![] };
        let orphans = live_orphans(&g, "warehouse", &["ghost_table".to_string()]);
        assert_eq!(orphans.len(), 1);
        assert_eq!(orphans[0].id, NodeId::new("db:warehouse", "ghost_table"));
        assert_eq!(orphans[0].kind, NodeKind::Relation);
        assert_eq!(orphans[0].title, "ghost_table");
    }

    #[test]
    fn live_orphans_skips_a_name_the_graph_already_explains() {
        let rel = relation("warehouse", "orders");
        let g = Graph { nodes: vec![rel.clone()], edges: vec![produces(("a", "setup"), &rel.id)] };
        assert!(live_orphans(&g, "warehouse", &["orders".to_string()]).is_empty());
    }

    #[test]
    fn live_orphans_dedupes_a_name_listed_twice() {
        let g = Graph { nodes: vec![], edges: vec![] };
        let orphans = live_orphans(&g, "warehouse", &["ghost_table".to_string(), "ghost_table".to_string()]);
        assert_eq!(orphans.len(), 1);
    }

    #[test]
    fn live_orphans_is_scoped_to_its_own_database() {
        // A relation this graph already explains in `staging` is still an
        // orphan when `--live` lists `warehouse`: a `db:NAME` namespace
        // belongs to one database (`NodeId`'s own doc comment), so the same
        // bare name in a different database is a different node.
        let rel = relation("staging", "orders");
        let g = Graph { nodes: vec![rel.clone()], edges: vec![produces(("a", "setup"), &rel.id)] };
        let orphans = live_orphans(&g, "warehouse", &["orders".to_string()]);
        assert_eq!(orphans.len(), 1);
        assert_eq!(orphans[0].id, NodeId::new("db:warehouse", "orders"));
    }

    fn link(from: (&str, &str), to: (&str, &str)) -> Edge {
        Edge {
            from: NodeId::new(from.0, from.1),
            to: NodeId::new(to.0, to.1),
            kind: EdgeKind::Link,
            line: 0,
            reciprocated: false,
        }
    }

    fn contains(from: (&str, &str), to: (&str, &str)) -> Edge {
        Edge {
            from: NodeId::new(from.0, from.1),
            to: NodeId::new(to.0, to.1),
            kind: EdgeKind::Contains,
            line: 0,
            reciprocated: false,
        }
    }

    #[test]
    fn outgoing_and_incoming_links_are_partitioned_by_direction() {
        let g = Graph { nodes: vec![], edges: vec![link(("a", "a"), ("b", "b"))] };
        assert_eq!(links_for(&g, &NodeId::new("a", "a")).outgoing, vec![NodeId::new("b", "b")]);
        assert_eq!(links_for(&g, &NodeId::new("b", "b")).backlinks, vec![NodeId::new("a", "a")]);
    }

    #[test]
    fn produces_and_reads_partition_by_kind_and_side() {
        let rel = relation("warehouse", "orders");
        let g = Graph {
            nodes: vec![rel.clone()],
            edges: vec![
                produces(("a", "setup"), &rel.id),
                Edge { from: rel.id.clone(), to: NodeId::new("b", "report"), kind: EdgeKind::Reads, line: 0, reciprocated: false },
            ],
        };
        assert_eq!(links_for(&g, &NodeId::new("a", "setup")).produces, vec![rel.id.clone()]);
        assert_eq!(links_for(&g, &NodeId::new("b", "report")).reads, vec![rel.id]);
    }

    #[test]
    fn containment_edges_are_never_counted_as_links() {
        let g = Graph { nodes: vec![], edges: vec![contains(("a", "a"), ("a", "b"))] };
        assert_eq!(links_for(&g, &NodeId::new("a", "a")), NodeLinks::default());
        assert_eq!(links_for(&g, &NodeId::new("a", "b")), NodeLinks::default());
    }

    #[test]
    fn a_node_touching_nothing_returns_every_field_empty() {
        let g = Graph { nodes: vec![], edges: vec![] };
        assert_eq!(links_for(&g, &NodeId::new("a", "a")), NodeLinks::default());
    }
}
