// generated by `dankg tangle` from src/graph/resolve.md -- do not edit

//! Link resolution and root containment.
//!
//! Resolution runs once the whole corpus is parsed, because a link's target may
//! live in a file that had not been read when the link was found, and because
//! backlinks are only honest when every file has been seen.
//!
//! The root is a hard boundary. A link that escapes it is refused rather than
//! followed. "an LLM can run it for you" means the markdown being graphed is
//! frequently untrusted input.

use super::build::{file_stem, strip_extension, ParsedFile, RawLink, Target};
use super::model::{Edge, EdgeKind, Graph, Node, NodeId, NodeKind};
use super::slug::slugify;
use crate::diag::Diags;

pub fn resolve(files: &[ParsedFile], diags: &mut Diags) -> Graph {
    let mut graph = Graph::default();

    for file in files {
        graph.nodes.extend(file.nodes.iter().cloned());
        graph.edges.extend(file.containment.iter().cloned());
    }

    for file in files {
        for link in &file.links {
            match resolve_one(file, link, files, diags) {
                Resolution::Found(to) => graph.edges.push(Edge {
                    from: link.from.clone(),
                    to,
                    kind: EdgeKind::Link,
                    line: link.line,
                    reciprocated: false,
                }),
                Resolution::Dangling(node) => {
                    let id = node.id.clone();
                    if !graph.contains(&id) {
                        graph.nodes.push(node);
                    }
                    graph.edges.push(Edge {
                        from: link.from.clone(),
                        to: id,
                        kind: EdgeKind::Link,
                        line: link.line,
                        reciprocated: false,
                    });
                }
                Resolution::Refused => {}
            }
        }
    }

    graph.reciprocate();
    graph.sort();
    graph
}

enum Resolution {
    Found(NodeId),
    /// The target does not exist. It still becomes a node. A dangling link is
    /// how you see what you have referenced but not yet written.
    Dangling(Node),
    /// Outside the root. Not followed, and not graphed.
    Refused,
}

fn resolve_one(
    file: &ParsedFile,
    link: &RawLink,
    files: &[ParsedFile],
    diags: &mut Diags,
) -> Resolution {
    match &link.target {
        Target::Path(dest) => resolve_path(file, link, dest, files, diags),
        Target::Wiki(target) => resolve_wiki(file, link, target, files, diags),
    }
}

fn resolve_path(
    file: &ParsedFile,
    link: &RawLink,
    dest: &str,
    files: &[ParsedFile],
    diags: &mut Diags,
) -> Resolution {
    let (path_part, fragment) = split_fragment(dest);

    // A bare `#fragment` addresses the current file.
    if path_part.is_empty() {
        return match find_slug(file, fragment) {
            Some(id) => Resolution::Found(id),
            None => {
                diags.warn_in(
                    &file.path,
                    link.line,
                    format!("no heading `{fragment}` in this file"),
                );
                Resolution::Dangling(placeholder(&file.key, fragment, &file.path))
            }
        };
    }

    let Some(joined) = join_normalize(dir_of(&file.path), path_part) else {
        diags.warn_in(
            &file.path,
            link.line,
            format!("`{path_part}` escapes the root, not followed"),
        );
        return Resolution::Refused;
    };

    let key = strip_extension(&joined);
    let Some(target_file) = files.iter().find(|f| f.key == key) else {
        diags.warn_in(&file.path, link.line, format!("file not found: `{path_part}`"));
        let slug = if fragment.is_empty() { file_stem(&key).to_string() } else { fragment.to_string() };
        return Resolution::Dangling(placeholder(&key, &slug, &joined));
    };

    if fragment.is_empty() {
        return match target_file.entry_node() {
            Some(node) => Resolution::Found(node.id.clone()),
            None => Resolution::Dangling(placeholder(&key, file_stem(&key), &target_file.path)),
        };
    }

    match find_slug(target_file, fragment) {
        Some(id) => Resolution::Found(id),
        None => {
            diags.warn_in(
                &file.path,
                link.line,
                format!("no heading `{fragment}` in `{}`", target_file.path),
            );
            Resolution::Dangling(placeholder(&key, fragment, &target_file.path))
        }
    }
}

fn resolve_wiki(
    file: &ParsedFile,
    link: &RawLink,
    target: &str,
    files: &[ParsedFile],
    diags: &mut Diags,
) -> Resolution {
    let (name, fragment) = split_fragment(target);

    // `[[#Heading]]` addresses the current file.
    if name.is_empty() {
        return match find_slug(file, fragment) {
            Some(id) => Resolution::Found(id),
            None => {
                diags.warn_in(&file.path, link.line, format!("no heading `{fragment}` in this file"));
                Resolution::Dangling(placeholder(&file.key, fragment, &file.path))
            }
        };
    }

    // `[[other#Heading]]`: find the file by stem or alias, then the heading.
    if !fragment.is_empty() {
        let matches = files_named(files, name);
        let Some(target_file) = pick(&matches, file, link, name, diags) else {
            diags.warn_in(&file.path, link.line, format!("no file named `{name}`"));
            return Resolution::Dangling(placeholder(name, fragment, name));
        };
        return match find_slug(target_file, fragment) {
            Some(id) => Resolution::Found(id),
            None => {
                diags.warn_in(
                    &file.path,
                    link.line,
                    format!("no heading `{fragment}` in `{}`", target_file.path),
                );
                Resolution::Dangling(placeholder(&target_file.key, fragment, &target_file.path))
            }
        };
    }

    // `[[Heading]]`: a slug search across the corpus comes first, since the
    // wikilink form is written to address headings.
    let wanted = slugify(name);
    let mut hits: Vec<&Node> = files
        .iter()
        .flat_map(|f| f.nodes.iter())
        .filter(|n| n.id.slug == wanted)
        .collect();
    hits.sort_by(|a, b| a.id.cmp(&b.id));

    if let Some(first) = hits.first() {
        if hits.len() > 1 {
            diags.warn_in(
                &file.path,
                link.line,
                format!(
                    "`[[{name}]]` is ambiguous ({} matches), using `{}`",
                    hits.len(),
                    first.id
                ),
            );
        }
        return Resolution::Found(first.id.clone());
    }

    // Fall back to a file of that name, so `[[ideas]]` finds ideas.md even when
    // no heading slugifies to "ideas".
    let matches = files_named(files, name);
    if let Some(target_file) = pick(&matches, file, link, name, diags) {
        if let Some(node) = target_file.entry_node() {
            return Resolution::Found(node.id.clone());
        }
    }

    diags.warn_in(&file.path, link.line, format!("unresolved wikilink `[[{name}]]`"));
    Resolution::Dangling(placeholder(name, &wanted, name))
}

fn files_named<'a>(files: &'a [ParsedFile], name: &str) -> Vec<&'a ParsedFile> {
    let mut out: Vec<&ParsedFile> = files
        .iter()
        .filter(|f| {
            file_stem(&f.key).eq_ignore_ascii_case(name)
                || f.aliases.iter().any(|a| a.eq_ignore_ascii_case(name))
        })
        .collect();
    out.sort_by(|a, b| a.key.cmp(&b.key));
    out
}

/// Ambiguity is reported, then settled by taking the lexicographically first
/// path, so the graph stays deterministic.
fn pick<'a>(
    matches: &[&'a ParsedFile],
    from: &ParsedFile,
    link: &RawLink,
    name: &str,
    diags: &mut Diags,
) -> Option<&'a ParsedFile> {
    let first = matches.first()?;
    if matches.len() > 1 {
        diags.warn_in(
            &from.path,
            link.line,
            format!("`{name}` is ambiguous ({} files), using `{}`", matches.len(), first.path),
        );
    }
    Some(first)
}

fn find_slug(file: &ParsedFile, fragment: &str) -> Option<NodeId> {
    let wanted = slugify(fragment);
    file.nodes
        .iter()
        .find(|n| n.id.slug == wanted || n.id.slug == fragment)
        .map(|n| n.id.clone())
}

fn placeholder(key: &str, slug: &str, path: &str) -> Node {
    let slug = if slug.is_empty() { "section".to_string() } else { slugify(slug) };
    Node {
        id: NodeId::new(key, &slug),
        title: slug.replace('-', " "),
        file: path.to_string(),
        line: 0,
        end_line: 0,
        level: 0,
        parent: None,
        tags: Vec::new(),
        external: Vec::new(),
        resolved: false,
        // A dangling link always points at a heading-shaped target. A
        // block is never something `[text](file#name)` can name. So a
        // placeholder invented to receive one is a placeholder heading.
        kind: NodeKind::Heading,
    }
}

fn split_fragment(dest: &str) -> (&str, &str) {
    match dest.split_once('#') {
        Some((path, fragment)) => (path.trim(), fragment.trim()),
        None => (dest.trim(), ""),
    }
}

/// The root-relative directory a root-relative file path sits in. Shared
/// with `eval::plan`'s cross-file `deps=` resolution, so a dependency and a
/// written link agree about what a relative path means without a second
/// implementation of "relative to this file" to keep in step.
pub(crate) fn dir_of(path: &str) -> &str {
    match path.rfind('/') {
        Some(i) => &path[..i],
        None => "",
    }
}

/// Join a relative link onto the linking file's directory and normalize it.
/// Returns `None` when the result climbs above the root. Also `eval::plan`'s
/// only way to turn a cross-file `deps=other.md#name` entry into the file it
/// names -- the same boundary refusal a written link already gets, reused
/// rather than reimplemented.
pub(crate) fn join_normalize(base_dir: &str, rel: &str) -> Option<String> {
    let mut parts: Vec<&str> = Vec::new();

    let segments = if rel.starts_with('/') {
        // A root-relative link is taken as relative to the root itself.
        rel.trim_start_matches('/').split('/').collect::<Vec<_>>()
    } else {
        base_dir
            .split('/')
            .chain(rel.split('/'))
            .collect::<Vec<_>>()
    };

    for segment in segments {
        match segment {
            "" | "." => {}
            ".." => {
                if parts.pop().is_none() {
                    return None;
                }
            }
            other => parts.push(other),
        }
    }

    Some(parts.join("/"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::build;
    use crate::md::Document;

    fn corpus(files: &[(&str, &str)]) -> (Vec<ParsedFile>, Diags) {
        let mut diags = Diags::new("corpus");
        let parsed: Vec<ParsedFile> = files
            .iter()
            .map(|(path, src)| {
                let mut d = Diags::new(*path);
                let doc = Document::parse(src, &mut d);
                diags.absorb(d);
                build::build(path, &doc, src.lines().count() as u32)
            })
            .collect();
        (parsed, diags)
    }

    fn graph_of(files: &[(&str, &str)]) -> (Graph, Diags) {
        let (parsed, mut diags) = corpus(files);
        let g = resolve(&parsed, &mut diags);
        (g, diags)
    }

    fn links(g: &Graph) -> Vec<(String, String, bool)> {
        g.edges
            .iter()
            .filter(|e| e.kind == EdgeKind::Link)
            .map(|e| (e.from.to_string(), e.to.to_string(), e.reciprocated))
            .collect()
    }

    #[test]
    fn same_file_fragment() {
        let (g, d) = graph_of(&[("a.md", "# One\n\n[go](#two)\n\n# Two\n")]);
        assert_eq!(links(&g), vec![("a#one".into(), "a#two".into(), false)]);
        assert!(d.is_empty());
    }

    #[test]
    fn cross_file_with_fragment() {
        let (g, d) = graph_of(&[
            ("notes/a.md", "# One\n\n[go](b.md#two)\n"),
            ("notes/b.md", "# Two\n"),
        ]);
        assert_eq!(links(&g), vec![("notes/a#one".into(), "notes/b#two".into(), false)]);
        assert!(d.is_empty());
    }

    #[test]
    fn relative_paths_normalize() {
        let (g, d) = graph_of(&[
            ("notes/deep/a.md", "# One\n\n[go](../b.md)\n"),
            ("notes/b.md", "# Two\n"),
        ]);
        assert_eq!(links(&g), vec![("notes/deep/a#one".into(), "notes/b#two".into(), false)]);
        assert!(d.is_empty());
    }

    #[test]
    fn bare_file_link_lands_on_first_heading() {
        let (g, _) = graph_of(&[("a.md", "# One\n\n[go](b.md)\n"), ("b.md", "# First\n\n# Second\n")]);
        assert_eq!(links(&g)[0].1, "b#first");
    }

    #[test]
    fn escaping_the_root_is_refused_not_followed() {
        let (g, d) = graph_of(&[("a.md", "# One\n\n[bad](../../etc/passwd.md)\n")]);
        assert!(links(&g).is_empty(), "no edge is created");
        assert!(d.items()[0].message.contains("escapes the root"));
    }

    #[test]
    fn missing_file_becomes_a_placeholder_with_a_warning() {
        let (g, d) = graph_of(&[("a.md", "# One\n\n[go](ideas.md#future)\n")]);
        let target = g.node(&NodeId::new("ideas", "future")).expect("placeholder exists");
        assert!(!target.resolved);
        assert!(d.items()[0].message.contains("file not found"));
        assert_eq!(d.items()[0].line, 3);
    }

    #[test]
    fn missing_heading_in_an_existing_file_warns() {
        let (g, d) = graph_of(&[("a.md", "# One\n\n[go](b.md#nope)\n"), ("b.md", "# Two\n")]);
        assert!(!g.node(&NodeId::new("b", "nope")).unwrap().resolved);
        assert!(d.items()[0].message.contains("no heading `nope`"));
    }

    #[test]
    fn wikilink_resolves_by_heading_slug() {
        let (g, d) = graph_of(&[("a.md", "# One\n\n[[Code Eval]]\n"), ("b.md", "# Code Eval\n")]);
        assert_eq!(links(&g)[0].1, "b#code-eval");
        assert!(d.is_empty());
    }

    #[test]
    fn wikilink_falls_back_to_file_name() {
        let (g, d) = graph_of(&[("a.md", "# One\n\n[[ideas]]\n"), ("ideas.md", "# Unrelated Title\n")]);
        assert_eq!(links(&g)[0].1, "ideas#unrelated-title");
        assert!(d.is_empty());
    }

    #[test]
    fn wikilink_with_fragment_finds_file_then_heading() {
        let (g, _) = graph_of(&[("a.md", "# One\n\n[[b#Two]]\n"), ("x/b.md", "# Two\n")]);
        assert_eq!(links(&g)[0].1, "x/b#two");
    }

    #[test]
    fn ambiguous_wikilink_warns_and_picks_first_path() {
        let (g, d) = graph_of(&[
            ("a.md", "# Start\n\n[[Shared]]\n"),
            ("z.md", "# Shared\n"),
            ("m.md", "# Shared\n"),
        ]);
        assert_eq!(links(&g)[0].1, "m#shared");
        assert!(d.items()[0].message.contains("ambiguous"));
    }

    #[test]
    fn alias_resolves_a_wikilink() {
        let (g, d) = graph_of(&[
            ("a.md", "# One\n\n[[arch#Two]]\n"),
            ("b.md", "---\nalias: arch\n---\n# Two\n"),
        ]);
        assert_eq!(links(&g)[0].1, "b#two");
        assert!(d.is_empty());
    }

    #[test]
    fn mutual_links_are_reciprocated() {
        let (g, _) = graph_of(&[
            ("a.md", "# One\n\n[go](b.md#two)\n"),
            ("b.md", "# Two\n\n[back](a.md#one)\n"),
        ]);
        assert!(links(&g).iter().all(|(_, _, recip)| *recip));
    }

    #[test]
    fn containment_edges_survive_resolution() {
        let (g, _) = graph_of(&[("a.md", "# One\n\n## Two\n")]);
        let contains: Vec<_> = g.edges.iter().filter(|e| e.kind == EdgeKind::Contains).collect();
        assert_eq!(contains.len(), 1);
        assert_eq!(contains[0].from.to_string(), "a#one");
    }

    #[test]
    fn output_is_deterministic() {
        let files = [("b.md", "# Two\n\n[x](a.md#one)\n"), ("a.md", "# One\n")];
        let (g1, _) = graph_of(&files);
        let mut reversed = files;
        reversed.reverse();
        let (g2, _) = graph_of(&reversed);
        assert_eq!(g1, g2);
    }
}
