# generated by `dankg tangle` from example/data_example/index.md ("Massachusetts Population 65 and Older, by County") -- do not edit

# /// script
# requires-python = ">=3.11"
# dependencies = ["pygris", "pandas"]
# ///
import os
import sys

import pandas as pd
from pygris import counties
from pygris.data import get_census

CENSUS_API_KEY = os.environ.get("CENSUS_API_KEY")
if not CENSUS_API_KEY:
    sys.exit(
        "CENSUS_API_KEY is not set -- see \"Getting a Census API key\" above."
    )

STATE_FIPS = "25"  # Massachusetts
YEAR = 2022  # most recent ACS 5-year estimates at the time of writing
ma_counties = counties(state="MA", cb=True, year=YEAR, cache=True)[["GEOID", "NAME"]]
AGE_VARS = [
    "B01001_001E",  # total population
    "B01001_020E", "B01001_021E", "B01001_022E", "B01001_023E", "B01001_024E", "B01001_025E",  # male, 65 and over
    "B01001_044E", "B01001_045E", "B01001_046E", "B01001_047E", "B01001_048E", "B01001_049E",  # female, 65 and over
]

age_data = get_census(
    dataset="acs/acs5",
    variables=AGE_VARS,
    year=YEAR,
    params={"for": "county:*", "in": f"state:{STATE_FIPS}", "key": CENSUS_API_KEY},
    return_geoid=True,
    guess_dtypes=True,
)
SENIOR_VARS = [v for v in AGE_VARS if v != "B01001_001E"]

report = ma_counties.merge(age_data, on="GEOID")
report["population_65_plus"] = report[SENIOR_VARS].sum(axis=1)
report["pct_65_plus"] = (report["population_65_plus"] / report["B01001_001E"] * 100).round(1)

report = (
    report.rename(columns={"NAME": "county", "B01001_001E": "total_population"})
    [["county", "total_population", "population_65_plus", "pct_65_plus"]]
    .sort_values("pct_65_plus", ascending=False)
    .reset_index(drop=True)
)
print(report.to_string(index=False))
