// generated by `dankg tangle` from src/weave.md -- do not edit

//! `dankg weave`: turns one markdown file into a readable document, HTML
//! or PDF via Typst. Single-file only (plan-weave.md decision 41) --
//! there is no corpus-walk branch, the same single-file path
//! `tangle::run`/`eval` already take for the identical reason.

use crate::cmd;
use crate::config::Config;
use crate::data::bib::{self, BibEntry};
use crate::diag::Diags;
use crate::eval::files::Files;
use crate::eval::session::corpus_graph_if_needed;
use crate::eval::{plan, result};
use crate::graph::build::{file_stem, strip_extension};
use crate::graph::index;
use crate::graph::slug::Slugger;
use crate::md::{Block, Document, Inline};
use crate::render::typst::BibliographySummary;
use crate::render::{typst, weave_html};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    Html,
    Pdf,
}

pub struct Report {
    /// Where the rendered page went: a file path, or `None` for stdout
    /// (HTML's own default with no `-o`).
    pub output: Option<PathBuf>,
    /// PDF only: the `.typ` source's own path. Always written, whether or
    /// not a PDF actually got compiled from it.
    pub typ_path: Option<PathBuf>,
    /// PDF only: whether `[weave.pdf] command` actually ran and produced
    /// one.
    pub pdf_written: bool,
}

pub fn run(path: &str, format: Format, output: Option<&str>, toc: bool, figures_outside: bool) -> Result<Report, String> {
    let source = fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
    let mut diags = Diags::new(path);
    let mut doc = Document::parse(&source, &mut diags);

    let abs_path = index::absolute(Path::new(path));
    let root = index::discover_root(&abs_path)
        .unwrap_or_else(|| abs_path.parent().map(PathBuf::from).unwrap_or_else(|| PathBuf::from(".")));
    let mut cfg_diags = Diags::new(".dankg/config");
    let config = Config::load(&root, &mut cfg_diags);
    diags.absorb(cfg_diags);

    let name = file_stem(&strip_extension(path)).to_string();
    let title = doc.frontmatter.title().map(str::to_string).unwrap_or_else(|| name.clone());

    let entry_rel = abs_path.strip_prefix(&root).map(index::to_slash).unwrap_or_else(|_| path.to_string());
    warn_stale_pairs(&doc, path, &entry_rel, &root, &config, &mut diags);
    if doc.frontmatter.cover() == Some(true) {
        drop_repeated_title_heading(&mut doc, &title);
    }
    let (tables, images) = produced_artifacts(&doc, &entry_rel, &root, &mut diags);
    let (labels, numbers) = figures(&doc, &tables, &images, &mut diags);
    let slugs = heading_slugs(&doc);
    let (typst_refs, html_refs) = references(&doc, &tables, &labels, &numbers, &slugs);
    let unresolved = resolve_references(&doc, &typst_refs, &labels, &numbers, &mut diags);
    let bib = bibliography(&doc, &entry_rel, &root, &mut diags);

    // Every reference is reported before anything is rendered, so one run
    // shows an author every bad line rather than the first (decision 64).
    if unresolved > 0 {
        diags.sort();
        diags.emit();
        return Err(format!("{unresolved} unresolved reference(s); nothing rendered"));
    }

    let report = match format {
        Format::Html => {
            render_html(
                &doc, &title, &config, &root, &tables, &images, &labels, &numbers, &slugs, &html_refs,
                bib.as_ref(), output, figures_outside, &mut diags,
            )?
        }
        Format::Pdf => render_pdf(
            &doc, &title, &config, &root, &name, &tables, &images, &labels, &slugs, &typst_refs, bib.as_ref(),
            output, toc, figures_outside, &mut diags,
        )?,
    };

    diags.sort();
    diags.emit();
    Ok(report)
}

fn drop_repeated_title_heading(doc: &mut Document, title: &str) {
    let repeats = matches!(
        doc.blocks.first(),
        Some(Block::Heading { inlines, .. }) if Inline::plain(inlines).trim() == title.trim()
    );
    if repeats {
        doc.blocks.remove(0);
    }
}

fn warn_stale_pairs(doc: &Document, path: &str, entry_rel: &str, root: &Path, config: &Config, diags: &mut Diags) {
    let mut discover_diags = Diags::new(entry_rel);
    let mut files = Files::new(root.to_path_buf());
    if files.discover(entry_rel, &mut discover_diags).is_err() {
        return;
    }
    let (files, graph) = match corpus_graph_if_needed(path, files) {
        Ok(v) => v,
        Err(e) => {
            diags.warn(0, format!("could not check eval result staleness: {e}"));
            return;
        }
    };
    let all_blocks = files.all_blocks();
    let mut xdep_cache = std::collections::HashMap::new();

    for b in plan::top_level_blocks(doc, entry_rel) {
        let Some(stored) = result::recorded_hash(doc, b.index, b.name) else { continue };
        let outcome = (|| {
            let chain = plan::plan_for(&all_blocks, entry_rel, b.name).map_err(|e| e.to_string())?;
            let hash_template = result::hash_template_for(config, &chain)?;
            result::is_stale(&files, config, &all_blocks, graph.as_ref(), &chain, &hash_template, stored, &mut xdep_cache)
        })();
        match outcome {
            Ok(false) => {}
            Ok(true) => diags.warn(b.line, format!("`{}` recorded result looks stale; rerun `dankg eval`", b.name)),
            Err(e) => diags.warn(b.line, format!("`{}` staleness could not be verified: {e}", b.name)),
        }
    }
}

fn produced_artifacts(
    doc: &Document,
    entry_rel: &str,
    root: &Path,
    diags: &mut Diags,
) -> (HashMap<usize, (String, String)>, HashMap<usize, (Vec<u8>, String)>) {
    let mut tables = HashMap::new();
    let mut images = HashMap::new();
    for b in plan::top_level_blocks(doc, entry_rel) {
        if result::recorded_hash(doc, b.index, b.name).is_none() {
            continue; // no recognized pair, nothing to attach an artifact to
        }
        let Some(raw) = b.produces else { continue };
        let Some(rel_path) = plan::parse_artifact(raw) else { continue };
        let Some(resolved) = plan::resolve_artifact(entry_rel, rel_path) else {
            diags.warn(b.line, format!("`{}` produces={raw} escapes the root; not rendered", b.name));
            continue;
        };
        if let Some(lang) = table_lang(rel_path) {
            match fs::read_to_string(root.join(&resolved)) {
                Ok(content) => {
                    tables.insert(b.index, (lang.to_string(), content));
                }
                Err(e) => diags.warn(b.line, format!("`{}` produces={raw} could not be read ({e}); not rendered", b.name)),
            }
        } else if image_ext(rel_path).is_some() {
            match fs::read(root.join(&resolved)) {
                Ok(bytes) => {
                    images.insert(b.index, (bytes, resolved));
                }
                Err(e) => diags.warn(b.line, format!("`{}` produces={raw} could not be read ({e}); not rendered", b.name)),
            }
        }
    }
    (tables, images)
}

/// The three extensions `code_or_data_table` already renders as a table
/// (decision 45); anything else is not a table shape this feature
/// knows how to show, so `produced_artifacts` leaves it out silently
/// rather than guessing.
fn table_lang(path: &str) -> Option<&'static str> {
    match path.rsplit('.').next()?.to_ascii_lowercase().as_str() {
        "csv" => Some("csv"),
        "tsv" => Some("tsv"),
        "json" => Some("json"),
        _ => None,
    }
}

/// The image extensions decision 51 knows how to render. `jpg`/`jpeg`
/// canonicalize to one tag: both mean the same MIME type, and both
/// renderers only ever need to know "this is a jpeg."
fn image_ext(path: &str) -> Option<&'static str> {
    match path.rsplit('.').next()?.to_ascii_lowercase().as_str() {
        "png" => Some("png"),
        "jpg" | "jpeg" => Some("jpg"),
        "gif" => Some("gif"),
        "svg" => Some("svg"),
        "webp" => Some("webp"),
        _ => None,
    }
}

/// Every figure's own label and number, by the block index its pair
/// starts at. The label is `label=` when the reader wrote one,
/// otherwise the block's own `name=` (decision 63). The number is
/// this figure's position among its own kind, counted in document
/// order (decision 65). A block with no artifact in `tables` or
/// `images` is not a figure (decision 54) and is in neither map. A
/// figure neither backend renders is in `labels` and not in
/// `numbers`: it keeps its name and takes no number.
fn figures(
    doc: &Document,
    tables: &HashMap<usize, (String, String)>,
    images: &HashMap<usize, (Vec<u8>, String)>,
    diags: &mut Diags,
) -> (HashMap<usize, String>, HashMap<usize, u32>) {
    let mut labels = HashMap::new();
    let mut numbers = HashMap::new();
    let mut claimed: HashMap<&str, u32> = HashMap::new();
    let (mut tables_seen, mut images_seen) = (0u32, 0u32);
    for (index, b) in doc.blocks.iter().enumerate() {
        let Block::Code { info, line, .. } = b else { continue };
        let is_table = tables.contains_key(&index);
        if !is_table && !images.contains_key(&index) {
            continue;
        }
        if !info.weave_hidden() && !info.weave_output_hidden() {
            let counter = if is_table { &mut tables_seen } else { &mut images_seen };
            *counter += 1;
            numbers.insert(index, *counter);
        }
        let Some(label) = info.label().or_else(|| info.name()) else { continue };
        if let Some(&first) = claimed.get(label) {
            diags.warn(
                *line,
                format!("figure label `{label}` is already used by the figure on line {first}; this one is dropped"),
            );
            continue;
        }
        claimed.insert(label, *line);
        labels.insert(index, label.to_string());
    }
    (labels, numbers)
}

/// Every heading's own slug, by its line. One `Slugger` for the whole
/// document, so a repeated heading title is suffixed exactly the way
/// `graph::build` already suffixes one (decision 62's own reservation
/// rule). Both backends read this, which is why it is built here
/// rather than inside either of them.
fn heading_slugs(doc: &Document) -> HashMap<u32, String> {
    let mut slugger = Slugger::new();
    doc.headings().iter().map(|(_, inlines, line)| (*line, slugger.assign(&Inline::plain(inlines)))).collect()
}

/// What each same-file fragment resolves to, for both backends
/// (decision 64). The first map is Typst's: a fragment's own label,
/// `fig:NAME` or `sec:SLUG`. The second is HTML's: a fragment's own
/// anchor id, and the text a bare reference to it shows. A figure with
/// no number is absent from both -- neither backend put it on the page.
fn references(
    doc: &Document,
    tables: &HashMap<usize, (String, String)>,
    labels: &HashMap<usize, String>,
    numbers: &HashMap<usize, u32>,
    slugs: &HashMap<u32, String>,
) -> (HashMap<String, String>, HashMap<String, (String, String)>) {
    let mut typst = HashMap::new();
    let mut html = HashMap::new();
    for (index, label) in labels {
        let Some(number) = numbers.get(index) else { continue };
        let kind = if tables.contains_key(index) { "Table" } else { "Figure" };
        typst.insert(label.clone(), format!("fig:{label}"));
        html.insert(label.clone(), (format!("fig-{label}"), format!("{kind} {number}")));
    }
    for (_, inlines, line) in doc.headings() {
        let Some(slug) = slugs.get(&line) else { continue };
        typst.entry(slug.clone()).or_insert_with(|| format!("sec:{slug}"));
        html.entry(slug.clone()).or_insert_with(|| (slug.clone(), Inline::plain(inlines).trim().to_string()));
    }
    (typst, html)
}

/// Every same-file reference in `doc`, checked against `refs`. Reports
/// each unresolved one at its own line and returns how many failed, so
/// `run` can walk the whole document before it gives up (decision 64).
fn resolve_references(
    doc: &Document,
    refs: &HashMap<String, String>,
    labels: &HashMap<usize, String>,
    numbers: &HashMap<usize, u32>,
    diags: &mut Diags,
) -> usize {
    let mut slices = Vec::new();
    walk_inlines(&doc.blocks, &mut slices);
    let mut found = Vec::new();
    for (line, inlines) in slices {
        collect_fragments(inlines, line, &mut found);
    }
    let mut failed = 0;
    for (fragment, line) in found {
        if refs.contains_key(&fragment) {
            continue;
        }
        failed += 1;
        diags.error(line, unresolved_message(doc, &fragment, labels, numbers));
    }
    failed
}

/// Every `[[#fragment]]` and `[text](#fragment)` in `inlines`, paired
/// with the enclosing block's own line. Recurses through emphasis and
/// through a link's own text, since a reference is legal inside either.
fn collect_fragments(inlines: &[Inline], line: u32, out: &mut Vec<(String, u32)>) {
    for i in inlines {
        match i {
            Inline::WikiLink { target, .. } => {
                if let Some(fragment) = target.strip_prefix('#') {
                    out.push((fragment.to_string(), line));
                }
            }
            Inline::Link { dest, text, .. } => {
                if let Some(fragment) = dest.strip_prefix('#') {
                    out.push((fragment.to_string(), line));
                }
                collect_fragments(text, line, out);
            }
            Inline::Emph { inner, .. } | Inline::Strong { inner, .. } => collect_fragments(inner, line, out),
            Inline::Text(_) | Inline::Code(_) | Inline::Citation { .. } => {}
            Inline::SoftBreak | Inline::HardBreak => {}
        }
    }
}

/// Why one fragment did not resolve. Three answers, because the next
/// action differs in each (decision 64).
fn unresolved_message(
    doc: &Document,
    fragment: &str,
    labels: &HashMap<usize, String>,
    numbers: &HashMap<usize, u32>,
) -> String {
    let hidden = labels.iter().find(|(index, label)| label.as_str() == fragment && !numbers.contains_key(index));
    if let Some((index, _)) = hidden {
        let how = match doc.blocks.get(*index) {
            Some(Block::Code { info, .. }) if info.weave_output_hidden() => "weave=output-hidden",
            _ => "weave=hidden",
        };
        return format!("`{fragment}` is a figure hidden by `{how}`; there is nothing on the page to point at");
    }
    if doc.named_blocks().iter().any(|(info, _, _)| info.name() == Some(fragment)) {
        return format!(
            "`{fragment}` names a block, but not a figure; only a captioned `produces=file:` artifact is one"
        );
    }
    format!("nothing in this document is named `{fragment}`")
}

pub struct Bibliography {
    /// Every parsed entry, external file first, fence second and winning a
    /// duplicate key -- keyed by its own citation key.
    pub entries: HashMap<String, BibEntry>,
    /// Cited keys in first-appearance order across the whole document.
    /// This *is* the numbering a rendered references list uses.
    pub order: Vec<String>,
    /// The merged raw Hayagriva text, written to disk for Typst to read
    /// directly -- `render::typst` never touches an entry's own fields.
    pub raw: String,
}

fn bibliography(doc: &Document, entry_rel: &str, root: &Path, diags: &mut Diags) -> Option<Bibliography> {
    let mut fences = Vec::new();
    find_hayagriva_fences(&doc.blocks, &mut fences);
    for &(_, line) in fences.iter().skip(1) {
        diags.warn(line, "more than one `hayagriva` fence in one document; only the first is used");
    }
    let fence = fences.into_iter().next();

    let external = doc.frontmatter.bibliography().and_then(|path| {
        let resolved = plan::resolve_artifact(entry_rel, path)?;
        match fs::read_to_string(root.join(&resolved)) {
            Ok(content) => Some((resolved, content)),
            Err(e) => {
                diags.warn(0, format!("bibliography={path} could not be read ({e}); ignored"));
                None
            }
        }
    });

    if fence.is_none() && external.is_none() {
        return None;
    }

    let mut entries: HashMap<String, BibEntry> = HashMap::new();
    let mut raw = String::new();

    if let Some((resolved, content)) = &external {
        let mut ext_diags = Diags::new(resolved.as_str());
        for e in bib::parse(content, &mut ext_diags) {
            entries.insert(e.key.clone(), e);
        }
        diags.absorb(ext_diags);
        raw.push_str(content);
    }

    if let Some((text, fence_line)) = fence {
        let mut fence_diags = Diags::new(entry_rel);
        let fence_entries = bib::parse(text, &mut fence_diags);
        // Relative to the fence's own content (decision 58's own module
        // boundary: a reusable parser knows nothing about its caller's
        // position) -- remapped here, the one place that position is
        // actually known.
        for d in fence_diags.items() {
            let mut remapped = d.clone();
            remapped.line += fence_line;
            diags.add(remapped);
        }
        for e in fence_entries {
            if entries.contains_key(&e.key) {
                diags.warn(
                    fence_line,
                    format!(
                        "bibliography key `{}` is defined in both the external file and the fence; the fence wins",
                        e.key
                    ),
                );
            }
            entries.insert(e.key.clone(), e);
        }
        if !raw.is_empty() {
            raw.push('\n');
        }
        raw.push_str(text);
    }

    let mut seen = HashSet::new();
    let mut order = Vec::new();
    let mut slices = Vec::new();
    walk_inlines(&doc.blocks, &mut slices);
    for (line, inlines) in slices {
        collect_citation_keys(inlines, line, &entries, &mut seen, &mut order, diags);
    }

    Some(Bibliography { entries, order, raw })
}

/// At most one is used; a second warns at its own caller. Recurses into a
/// list item's own blocks, the same full-document reach every walk here
/// gives weave -- a fence has no reason to live only at the top level.
fn find_hayagriva_fences<'a>(blocks: &'a [Block], out: &mut Vec<(&'a str, u32)>) {
    for b in blocks {
        match b {
            Block::Code { info, text, line, .. } if info.lang.as_deref() == Some("hayagriva") => {
                out.push((text.as_str(), *line));
            }
            Block::List(l) => {
                for item in &l.items {
                    find_hayagriva_fences(&item.blocks, out);
                }
            }
            _ => {}
        }
    }
}

/// Every inline-bearing block, paired with the enclosing block's own
/// `line` -- the finest position the AST tracks for one of its inlines,
/// used to attribute an unresolved citation to at least the right block
/// rather than nowhere at all.
fn walk_inlines<'a>(blocks: &'a [Block], out: &mut Vec<(u32, &'a [Inline])>) {
    for b in blocks {
        match b {
            Block::Heading { inlines, line, .. } | Block::Paragraph { inlines, line, .. } => {
                out.push((*line, inlines));
            }
            Block::Table { header, rows, line, .. } => {
                for cell in header {
                    out.push((*line, cell));
                }
                for row in rows {
                    for cell in row {
                        out.push((*line, cell));
                    }
                }
            }
            Block::List(l) => {
                for item in &l.items {
                    walk_inlines(&item.blocks, out);
                }
            }
            Block::Code { .. } | Block::ThematicBreak { .. } | Block::Passthrough { .. } => {}
        }
    }
}

fn collect_citation_keys(
    inlines: &[Inline],
    line: u32,
    entries: &HashMap<String, BibEntry>,
    seen: &mut HashSet<String>,
    order: &mut Vec<String>,
    diags: &mut Diags,
) {
    for i in inlines {
        match i {
            Inline::Citation { keys, .. } => {
                for k in keys {
                    if !entries.contains_key(k) {
                        diags.warn(line, format!("citation key `{k}` is not in the bibliography"));
                    }
                    if seen.insert(k.clone()) {
                        order.push(k.clone());
                    }
                }
            }
            Inline::Emph { inner, .. } | Inline::Strong { inner, .. } => {
                collect_citation_keys(inner, line, entries, seen, order, diags)
            }
            Inline::Link { text, .. } => collect_citation_keys(text, line, entries, seen, order, diags),
            Inline::Text(_) | Inline::Code(_) | Inline::WikiLink { .. } | Inline::SoftBreak | Inline::HardBreak => {}
        }
    }
}

fn read_asset(root: &Path, rel: &str, key: &str, diags: &mut Diags) -> Option<String> {
    let full = root.join(rel);
    match fs::read_to_string(&full) {
        Ok(text) => Some(text),
        Err(e) => {
            diags.warn(0, format!("[weave.*] {key} = {rel} could not be read ({e}); ignored"));
            None
        }
    }
}

fn render_html(
    doc: &Document,
    title: &str,
    config: &Config,
    root: &Path,
    tables: &HashMap<usize, (String, String)>,
    images: &HashMap<usize, (Vec<u8>, String)>,
    labels: &HashMap<usize, String>,
    numbers: &HashMap<usize, u32>,
    slugs: &HashMap<u32, String>,
    refs: &HashMap<String, (String, String)>,
    bibliography: Option<&Bibliography>,
    output: Option<&str>,
    figures_outside: bool,
    diags: &mut Diags,
) -> Result<Report, String> {
    let extra_css = config.weave("html").and_then(|w| w.css).and_then(|rel| read_asset(root, &rel, "css", diags));
    let html_bib = bibliography.map(|bib| weave_html::Bibliography { entries: &bib.entries, order: &bib.order });
    let rendered = weave_html::render(
        doc, title, extra_css.as_deref(), tables, images, labels, numbers, slugs, refs, figures_outside,
        html_bib.as_ref(), diags,
    );

    let written = match output {
        Some(p) => {
            let file = PathBuf::from(p);
            fs::write(&file, &rendered).map_err(|e| format!("{}: {e}", file.display()))?;
            Some(file)
        }
        None => {
            use std::io::Write;
            std::io::stdout().write_all(rendered.as_bytes()).map_err(|e| e.to_string())?;
            None
        }
    };
    Ok(Report { output: written, typ_path: None, pdf_written: false })
}

fn render_pdf(
    doc: &Document,
    title: &str,
    config: &Config,
    root: &Path,
    name: &str,
    tables: &HashMap<usize, (String, String)>,
    images: &HashMap<usize, (Vec<u8>, String)>,
    labels: &HashMap<usize, String>,
    slugs: &HashMap<u32, String>,
    refs: &HashMap<String, String>,
    bibliography: Option<&Bibliography>,
    output: Option<&str>,
    toc: bool,
    figures_outside: bool,
    diags: &mut Diags,
) -> Result<Report, String> {
    let build_dir = root.join(".dankg").join("build").join("weave");
    let assets_dir = build_dir.join("assets");
    let mut copied_images = images.clone();
    for (index, (bytes, resolved)) in images {
        let dest = assets_dir.join(resolved);
        let result = dest
            .parent()
            .map(fs::create_dir_all)
            .unwrap_or(Ok(()))
            .and_then(|()| fs::write(&dest, bytes));
        if let Err(e) = result {
            diags.warn(0, format!("could not copy `{resolved}` into the build directory ({e}); not rendered"));
            copied_images.remove(index);
        }
    }

    // The identical copy-before-compile shape `images` already gets
    // (decision 51): `render::typst` never touches a filesystem. The
    // merged raw text goes to disk here, before `typst::render` is asked
    // to emit a `#bibliography(...)` call pointing at it.
    let bib_summary = bibliography.and_then(|bib| {
        let dest = build_dir.join("bibliography.yml");
        match fs::create_dir_all(&build_dir).and_then(|()| fs::write(&dest, &bib.raw)) {
            Ok(()) => {
                Some(BibliographySummary { valid_keys: bib.entries.keys().cloned().collect(), asset_path: "bibliography.yml".to_string() })
            }
            Err(e) => {
                diags.warn(0, format!("could not write bibliography.yml into the build directory ({e}); not rendered"));
                None
            }
        }
    });

    let body = typst::render(
        doc, title, toc, tables, &copied_images, labels, slugs, refs, figures_outside, bib_summary.as_ref(), diags,
    );
    let weave_cfg = config.weave("pdf");
    let preamble =
        weave_cfg.as_ref().and_then(|w| w.template.clone()).and_then(|rel| read_asset(root, &rel, "template", diags));
    let content = match preamble {
        Some(p) => format!("{p}\n\n{body}"),
        None => body,
    };

    let typ_path = build_dir.join(format!("{name}.typ"));
    if let Some(parent) = typ_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
    }
    fs::write(&typ_path, &content).map_err(|e| format!("{}: {e}", typ_path.display()))?;

    let pdf_path = match output {
        Some(p) => PathBuf::from(p),
        None => build_dir.join(format!("{name}.pdf")),
    };
    if let Some(parent) = pdf_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
    }

    let mut pdf_written = false;
    if let Some(template) = weave_cfg.as_ref().and_then(|c| c.command.as_ref()) {
        spawn_pdf(template, &typ_path, &pdf_path)?;
        pdf_written = true;
    }

    Ok(Report {
        output: if pdf_written { Some(pdf_path) } else { None },
        typ_path: Some(typ_path),
        pdf_written,
    })
}

fn spawn_pdf(template: &str, typ_path: &Path, pdf_path: &Path) -> Result<(), String> {
    let typ = typ_path.to_string_lossy();
    let pdf = pdf_path.to_string_lossy();
    let Some(argv) = cmd::build(template, &[("typ", &typ), ("pdf", &pdf)]) else {
        return Err("`[weave.pdf] command` is empty once substituted".to_string());
    };
    let status = std::process::Command::new(&argv[0])
        .args(&argv[1..])
        .status()
        .map_err(|e| format!("could not run `{}`: {e}", argv[0]))?;
    if !status.success() {
        return Err("`[weave.pdf] command` exited with a failure".to_string());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write as _;
    use std::sync::atomic::{AtomicU64, Ordering};

    fn scratch(files: &[(&str, &str)]) -> PathBuf {
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!("dankg-weave-test-{}-{n}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        for (name, content) in files {
            let path = dir.join(name);
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            let mut f = fs::File::create(&path).unwrap();
            f.write_all(content.as_bytes()).unwrap();
        }
        dir
    }

    /// Every bad line in one run, and no file of any kind on disk
    /// (decision 64).
    #[test]
    fn three_unresolved_references_fail_the_weave_and_write_nothing() {
        let dir = scratch(&[("a.md", "# Intro\n\nSee [[#one]] and [[#two]] and [x](#three).\n")]);
        let out = dir.join("out.html");
        let result = run(dir.join("a.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false);
        let err = result.err().expect("an unresolved reference must fail the weave");
        assert!(err.contains("3 unresolved reference(s)"), "{err}");
        assert!(!out.exists(), "no page is written for a document that failed to resolve");
    }

    #[test]
    fn a_resolving_heading_reference_weaves_normally() {
        let dir = scratch(&[("a.md", "# Intro\n\nSee [[#intro]] and [the start](#intro).\n")]);
        let out = dir.join("out.html");
        run(dir.join("a.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("<a href=\"#intro\">Intro</a>"), "{content}");
        assert!(content.contains("<a href=\"#intro\">the start</a>"), "{content}");
    }

    /// A reference to a real figure resolves against the label decision 63
    /// gave it, and reads as the number decision 65 counted for it.
    #[test]
    fn a_figure_reference_resolves_end_to_end() {
        let dir = scratch(&[
            ("a.md", "```python name=t produces=file:data.csv caption=\"Revenue\"\nrun()\n```\n\n<!-- dankg:result name=t hash=0000000000000001 -->\n\n```\nok\n```\n\nSee [[#t]].\n"),
            ("data.csv", "x,y\n1,2\n"),
        ]);
        let out = dir.join("out.html");
        run(dir.join("a.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("<figure class=\"table-figure\" id=\"fig-t\">"), "{content}");
        assert!(content.contains("<figcaption>Table 1: Revenue</figcaption>"), "{content}");
        assert!(content.contains("<a href=\"#fig-t\">Table 1</a>"), "{content}");
    }

    #[test]
    fn html_with_no_output_path_still_reports_none() {
        let dir = scratch(&[("a.md", "# H\n\ntext\n")]);
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Html, None, true, false).unwrap();
        assert!(report.output.is_none());
        assert!(report.typ_path.is_none());
    }

    #[test]
    fn html_with_an_output_path_writes_a_file() {
        let dir = scratch(&[("a.md", "# H\n\ntext\n")]);
        let out = dir.join("out.html");
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        assert_eq!(report.output, Some(out.clone()));
        let content = fs::read_to_string(&out).unwrap();
        // The page's own title heading (from the file name, "a" -- no
        // frontmatter here) is distinct from the document's own "H"
        // heading, which keeps its slug-derived id.
        assert!(content.contains("<h1>a</h1>"), "{content}");
        assert!(content.contains("<h1 id=\"h\">H</h1>"), "{content}");
    }

    #[test]
    fn title_falls_back_to_the_file_name_with_no_frontmatter() {
        let dir = scratch(&[("notes.md", "text\n")]);
        let out = dir.join("out.html");
        run(dir.join("notes.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("<title>notes</title>"), "{content}");
    }

    #[test]
    fn frontmatter_title_wins_over_the_file_name() {
        let dir = scratch(&[("notes.md", "---\ntitle: Real Title\n---\ntext\n")]);
        let out = dir.join("out.html");
        run(dir.join("notes.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("<title>Real Title</title>"), "{content}");
    }

    #[test]
    fn cover_true_drops_a_leading_heading_that_repeats_the_title() {
        let dir = scratch(&[("notes.md", "---\ntitle: Real Title\ncover: true\n---\n# Real Title\n\ntext\n\n## Later\n")]);
        let out = dir.join("out.html");
        run(dir.join("notes.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("<h1>Real Title</h1>"), "the title block itself stays: {content}");
        assert!(!content.contains("<h1 id=\"real-title\">"), "the body's own repeat is gone: {content}");
        // Gone from the table of contents with it -- the TOC is built
        // from the same blocks the body is.
        assert!(!content.contains("#real-title"), "{content}");
        assert!(content.contains("#later"), "a heading further down is untouched: {content}");
    }

    #[test]
    fn cover_true_leaves_a_leading_heading_that_says_something_else() {
        let dir = scratch(&[("notes.md", "---\ntitle: Real Title\ncover: true\n---\n# Something Else\n")]);
        let out = dir.join("out.html");
        run(dir.join("notes.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("<h1 id=\"something-else\">Something Else</h1>"), "{content}");
    }

    #[test]
    fn no_cover_key_repeats_the_title_the_way_it_always_did() {
        let dir = scratch(&[("notes.md", "---\ntitle: Real Title\n---\n# Real Title\n")]);
        let out = dir.join("out.html");
        run(dir.join("notes.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("<h1>Real Title</h1>"), "{content}");
        assert!(content.contains("<h1 id=\"real-title\">Real Title</h1>"), "{content}");
    }

    #[test]
    fn cover_false_drops_the_title_block_and_keeps_the_document_heading() {
        let dir = scratch(&[("notes.md", "---\ntitle: Real Title\nauthor: Jane Doe\ncover: false\n---\n# Real Title\n")]);
        let out = dir.join("out.html");
        run(dir.join("notes.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(!content.contains("<h1>Real Title</h1>"), "the generated title block is gone: {content}");
        assert!(!content.contains("Jane Doe"), "its byline goes with it: {content}");
        assert!(content.contains("<h1 id=\"real-title\">Real Title</h1>"), "the document's own heading carries it: {content}");
        assert!(content.contains("<title>Real Title</title>"), "the tab still needs a name: {content}");
    }

    #[test]
    fn cover_false_drops_the_typst_cover_page() {
        let dir = scratch(&[("notes.md", "---\ntitle: Real Title\ncover: false\n---\n# Real Title\n")]);
        let report = run(dir.join("notes.md").to_str().unwrap(), Format::Pdf, None, true, false).unwrap();
        let typ = fs::read_to_string(report.typ_path.unwrap()).unwrap();
        assert!(!typ.contains("#pagebreak()"), "no cover page, so nothing to break after: {typ}");
        assert!(typ.starts_with("#outline()"), "{typ}");
        assert!(typ.contains("= Real Title"), "the document's own heading carries the title: {typ}");
    }

    #[test]
    fn cover_true_keeps_the_typst_cover_page_and_drops_the_repeat() {
        let dir = scratch(&[("notes.md", "---\ntitle: Real Title\ncover: true\n---\n# Real Title\n\ntext\n")]);
        let report = run(dir.join("notes.md").to_str().unwrap(), Format::Pdf, None, true, false).unwrap();
        let typ = fs::read_to_string(report.typ_path.unwrap()).unwrap();
        assert!(typ.contains("#text(size: 28pt, weight: \"bold\")[Real Title]"), "{typ}");
        assert!(!typ.contains("= Real Title"), "the body's own repeat is gone: {typ}");
    }

    #[test]
    fn configured_css_is_read_and_appended() {
        let dir = scratch(&[
            (".dankg/config", "[weave.html]\ncss = theme.css\n"),
            ("theme.css", "body { color: red; }"),
            ("a.md", "# H\n"),
        ]);
        let out = dir.join("out.html");
        run(dir.join("a.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false).unwrap();
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("color: red"), "{content}");
    }

    #[test]
    fn a_missing_css_file_warns_and_is_skipped_not_fatal() {
        let dir = scratch(&[(".dankg/config", "[weave.html]\ncss = nope.css\n"), ("a.md", "# H\n")]);
        let out = dir.join("out.html");
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Html, Some(out.to_str().unwrap()), true, false);
        assert!(report.is_ok());
    }

    #[test]
    fn pdf_always_writes_the_typ_even_unconfigured() {
        let dir = scratch(&[("a.md", "# H\n\ntext\n")]);
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Pdf, None, true, false).unwrap();
        assert!(report.typ_path.as_ref().unwrap().exists());
        assert!(!report.pdf_written);
        assert!(report.output.is_none());
    }

    #[test]
    fn pdf_typ_defaults_under_dankg_build_weave() {
        let dir = scratch(&[("a.md", "# H\n")]);
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Pdf, None, true, false).unwrap();
        assert_eq!(report.typ_path, Some(dir.join(".dankg/build/weave/a.typ")));
    }

    #[test]
    fn a_configured_command_runs_and_reports_the_pdf_path() {
        let dir = scratch(&[
            (".dankg/config", "[weave.pdf]\ncommand = sh -c 'touch {pdf}'\n"),
            ("a.md", "# H\n"),
        ]);
        let out = dir.join("out.pdf");
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Pdf, Some(out.to_str().unwrap()), true, false).unwrap();
        assert!(report.pdf_written);
        assert_eq!(report.output, Some(out.clone()));
        assert!(out.exists());
    }

    #[test]
    fn a_configured_template_is_prepended_to_the_typ() {
        let dir = scratch(&[
            (".dankg/config", "[weave.pdf]\ntemplate = template.typ\n"),
            ("template.typ", "#set page(margin: 2cm)"),
            ("a.md", "# H\n"),
        ]);
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Pdf, None, true, false).unwrap();
        let content = fs::read_to_string(report.typ_path.unwrap()).unwrap();
        let template_pos = content.find("#set page(margin: 2cm)").unwrap();
        let title_pos = content.find("= H").unwrap();
        assert!(template_pos < title_pos, "{content}");
    }

    #[test]
    fn a_missing_template_file_warns_and_the_typ_is_still_written() {
        let dir = scratch(&[(".dankg/config", "[weave.pdf]\ntemplate = nope.typ\n"), ("a.md", "# H\n")]);
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Pdf, None, true, false).unwrap();
        assert!(report.typ_path.unwrap().exists());
    }

    fn stale_scratch(hash_hex: &str) -> (PathBuf, Config) {
        let dir = scratch(&[
            (".dankg/config", "[lang.sh]\ncommand = sh {file}\n"),
            ("a.md", &format!("```sh name=a\necho hi\n```\n\n<!-- dankg:result name=a hash={hash_hex} -->\n\n```\nhi\n```\n")),
        ]);
        let config = Config::load(&dir, &mut Diags::new(".dankg/config"));
        (dir, config)
    }

    #[test]
    fn warn_stale_pairs_is_silent_when_the_recorded_result_is_current() {
        let (dir, config) = stale_scratch("0000000000000000");
        let source = fs::read_to_string(dir.join("a.md")).unwrap();
        let doc = Document::parse(&source, &mut Diags::new("a.md"));
        let blocks = plan::top_level_blocks(&doc, "a.md");
        let chain = plan::plan_for(&blocks, "a.md", "a").unwrap();
        let template = result::hash_template_for(&config, &chain).unwrap();
        let real_hash = result::expected_hash(&chain, &template, &[]);

        let source = fs::read_to_string(dir.join("a.md")).unwrap().replace("0000000000000000", &crate::hash::hex(real_hash));
        fs::write(dir.join("a.md"), &source).unwrap();
        let doc = Document::parse(&source, &mut Diags::new("a.md"));

        let mut diags = Diags::new("a.md");
        warn_stale_pairs(&doc, dir.join("a.md").to_str().unwrap(), "a.md", &dir, &config, &mut diags);
        assert!(diags.items().is_empty(), "{:?}", diags.items());
    }

    #[test]
    fn warn_stale_pairs_warns_when_the_source_changed_since_the_result_was_recorded() {
        let (dir, config) = stale_scratch("0000000000000000");
        let source = fs::read_to_string(dir.join("a.md")).unwrap();
        let doc = Document::parse(&source, &mut Diags::new("a.md"));

        let mut diags = Diags::new("a.md");
        warn_stale_pairs(&doc, dir.join("a.md").to_str().unwrap(), "a.md", &dir, &config, &mut diags);
        assert_eq!(diags.items().len(), 1, "{:?}", diags.items());
        assert!(diags.items()[0].message.contains("looks stale"), "{:?}", diags.items());
    }

    #[test]
    fn warn_stale_pairs_is_silent_for_a_named_block_with_no_recorded_result() {
        let dir = scratch(&[
            (".dankg/config", "[lang.sh]\ncommand = sh {file}\n"),
            ("a.md", "```sh name=a\necho hi\n```\n"),
        ]);
        let config = Config::load(&dir, &mut Diags::new(".dankg/config"));
        let source = fs::read_to_string(dir.join("a.md")).unwrap();
        let doc = Document::parse(&source, &mut Diags::new("a.md"));

        let mut diags = Diags::new("a.md");
        warn_stale_pairs(&doc, dir.join("a.md").to_str().unwrap(), "a.md", &dir, &config, &mut diags);
        assert!(diags.items().is_empty(), "{:?}", diags.items());
    }

    #[test]
    fn table_lang_recognizes_csv_tsv_json_case_insensitively() {
        assert_eq!(table_lang("data.csv"), Some("csv"));
        assert_eq!(table_lang("data.CSV"), Some("csv"));
        assert_eq!(table_lang("data.tsv"), Some("tsv"));
        assert_eq!(table_lang("data.json"), Some("json"));
        assert_eq!(table_lang("chart.png"), None);
        assert_eq!(table_lang("no_extension"), None);
    }

    #[test]
    fn produced_artifacts_reads_a_csv_artifact_for_a_recognized_pair() {
        let dir = scratch(&[
            ("a.md", "```python name=a produces=file:data.csv\nwrite_csv()\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\nwrote data.csv\n```\n"),
            ("data.csv", "x,y\n1,2\n"),
        ]);
        let source = fs::read_to_string(dir.join("a.md")).unwrap();
        let doc = Document::parse(&source, &mut Diags::new("a.md"));

        let mut diags = Diags::new("a.md");
        let (tables, images) = produced_artifacts(&doc, "a.md", &dir, &mut diags);
        assert_eq!(tables.get(&0), Some(&("csv".to_string(), "x,y\n1,2\n".to_string())));
        assert!(images.is_empty());
        assert!(diags.items().is_empty(), "{:?}", diags.items());
    }

    #[test]
    fn produced_artifacts_reads_a_png_artifact_for_a_recognized_pair() {
        let dir = scratch(&[(
            "a.md",
            "```python name=a produces=file:chart.png\nsavefig()\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\nwrote chart.png\n```\n",
        )]);
        fs::write(dir.join("chart.png"), [0xffu8, 0xd8, 0xff, 0xe0]).unwrap();
        let source = fs::read_to_string(dir.join("a.md")).unwrap();
        let doc = Document::parse(&source, &mut Diags::new("a.md"));

        let mut diags = Diags::new("a.md");
        let (tables, images) = produced_artifacts(&doc, "a.md", &dir, &mut diags);
        assert!(tables.is_empty());
        assert_eq!(images.get(&0), Some(&(vec![0xff, 0xd8, 0xff, 0xe0], "chart.png".to_string())));
        assert!(diags.items().is_empty(), "{:?}", diags.items());
    }

    #[test]
    fn produced_artifacts_is_silent_for_a_named_block_with_no_recorded_result() {
        let dir = scratch(&[("a.md", "```python name=a produces=file:data.csv\nwrite_csv()\n```\n"), ("data.csv", "x,y\n1,2\n")]);
        let source = fs::read_to_string(dir.join("a.md")).unwrap();
        let doc = Document::parse(&source, &mut Diags::new("a.md"));

        let mut diags = Diags::new("a.md");
        let (tables, images) = produced_artifacts(&doc, "a.md", &dir, &mut diags);
        assert!(tables.is_empty());
        assert!(images.is_empty());
        assert!(diags.items().is_empty(), "{:?}", diags.items());
    }

    #[test]
    fn produced_artifacts_warns_on_a_missing_artifact() {
        let dir = scratch(&[(
            "a.md",
            "```python name=a produces=file:missing.csv\nwrite_csv()\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\ndone\n```\n",
        )]);
        let source = fs::read_to_string(dir.join("a.md")).unwrap();
        let doc = Document::parse(&source, &mut Diags::new("a.md"));

        let mut diags = Diags::new("a.md");
        let (tables, images) = produced_artifacts(&doc, "a.md", &dir, &mut diags);
        assert!(tables.is_empty());
        assert!(images.is_empty());
        assert_eq!(diags.items().len(), 1, "{:?}", diags.items());
        assert!(diags.items()[0].message.contains("could not be read"), "{:?}", diags.items());
    }

    #[test]
    fn produced_artifacts_is_silent_for_an_unrecognized_extension() {
        let dir = scratch(&[(
            "a.md",
            "```python name=a produces=file:notes.txt\nwrite_notes()\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\ndone\n```\n",
        )]);
        let source = fs::read_to_string(dir.join("a.md")).unwrap();
        let doc = Document::parse(&source, &mut Diags::new("a.md"));

        let mut diags = Diags::new("a.md");
        let (tables, images) = produced_artifacts(&doc, "a.md", &dir, &mut diags);
        assert!(tables.is_empty());
        assert!(images.is_empty());
        assert!(diags.items().is_empty(), "{:?}", diags.items());
    }

    /// A pair with an artifact and no `label=` takes its own `name=`
    /// (decision 63).
    #[test]
    fn figures_defaults_to_the_blocks_own_name() {
        let d = doc("```python name=chart produces=file:chart.png\nsavefig()\n```\n\n<!-- dankg:result name=chart hash=0000000000000001 -->\n\n```\nwrote chart.png\n```\n");
        let mut images = HashMap::new();
        images.insert(0, (Vec::new(), "chart.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (labels, _) = figures(&d, &HashMap::new(), &images, &mut diags);
        assert_eq!(labels.get(&0), Some(&"chart".to_string()));
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    #[test]
    fn figures_prefers_a_reader_written_label_over_the_name() {
        let d = doc("```python name=chart label=revenue produces=file:chart.png\nsavefig()\n```\n\n<!-- dankg:result name=chart hash=0000000000000001 -->\n\n```\nwrote chart.png\n```\n");
        let mut images = HashMap::new();
        images.insert(0, (Vec::new(), "chart.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (labels, _) = figures(&d, &HashMap::new(), &images, &mut diags);
        assert_eq!(labels.get(&0), Some(&"revenue".to_string()));
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    /// A named block with no artifact is not a figure (decision 54), so
    /// there is nothing for a reference to point at and nothing to label.
    #[test]
    fn figures_skips_a_block_with_no_artifact() {
        let d = doc("```sh name=a\necho hi\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\nhi\n```\n");
        let mut diags = Diags::new("t.md");
        let (labels, _) = figures(&d, &HashMap::new(), &HashMap::new(), &mut diags);
        assert!(labels.is_empty());
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    /// A hidden figure keeps its label, so a later reference to it can be
    /// told apart from a reference to nothing at all.
    #[test]
    fn figures_keeps_a_hidden_figures_own_label() {
        let d = doc("```python name=chart weave=hidden produces=file:chart.png\nsavefig()\n```\n\n<!-- dankg:result name=chart hash=0000000000000001 -->\n\n```\nwrote chart.png\n```\n");
        let mut images = HashMap::new();
        images.insert(0, (Vec::new(), "chart.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (labels, _) = figures(&d, &HashMap::new(), &images, &mut diags);
        assert_eq!(labels.get(&0), Some(&"chart".to_string()));
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    #[test]
    fn a_colliding_label_warns_by_line_and_the_second_one_is_dropped() {
        let d = doc("```python name=a label=chart produces=file:one.png\nsavefig()\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\nwrote one.png\n```\n\n```python name=b label=chart produces=file:two.png\nsavefig()\n```\n\n<!-- dankg:result name=b hash=0000000000000002 -->\n\n```\nwrote two.png\n```\n");
        let mut images = HashMap::new();
        images.insert(0, (Vec::new(), "one.png".to_string()));
        images.insert(3, (Vec::new(), "two.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (labels, _) = figures(&d, &HashMap::new(), &images, &mut diags);
        assert_eq!(labels.get(&0), Some(&"chart".to_string()));
        assert_eq!(labels.get(&3), None, "the second claim is dropped, not suffixed");
        assert_eq!(diags.items().len(), 1, "{:?}", diags.items());
        assert_eq!(diags.items()[0].line, 11, "{:?}", diags.items());
        assert!(diags.items()[0].message.contains("already used by the figure on line 1"), "{:?}", diags.items());
    }

    /// A `label=` colliding with another block's own defaulted `name=`
    /// collides just the same. The rule is about the label that comes
    /// out, not about which attribute it came from.
    #[test]
    fn a_label_colliding_with_a_defaulted_name_collides_too() {
        let d = doc("```python name=chart produces=file:one.png\nsavefig()\n```\n\n<!-- dankg:result name=chart hash=0000000000000001 -->\n\n```\nwrote one.png\n```\n\n```python name=b label=chart produces=file:two.png\nsavefig()\n```\n\n<!-- dankg:result name=b hash=0000000000000002 -->\n\n```\nwrote two.png\n```\n");
        let mut images = HashMap::new();
        images.insert(0, (Vec::new(), "one.png".to_string()));
        images.insert(3, (Vec::new(), "two.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (labels, _) = figures(&d, &HashMap::new(), &images, &mut diags);
        assert_eq!(labels.get(&0), Some(&"chart".to_string()));
        assert_eq!(labels.get(&3), None);
        assert_eq!(diags.items().len(), 1, "{:?}", diags.items());
    }

    /// Typst counts a table and an image on two separate counters, so
    /// this walk does too (decision 65). A single counter would disagree
    /// with the PDF on exactly this document.
    #[test]
    fn figures_numbers_each_kind_on_its_own_counter() {
        let d = doc("```python name=t1 produces=file:a.csv\nrun()\n```\n\n<!-- dankg:result name=t1 hash=0000000000000001 -->\n\n```\nok\n```\n\n```python name=i1 produces=file:a.png\nrun()\n```\n\n<!-- dankg:result name=i1 hash=0000000000000002 -->\n\n```\nok\n```\n\n```python name=t2 produces=file:b.csv\nrun()\n```\n\n<!-- dankg:result name=t2 hash=0000000000000003 -->\n\n```\nok\n```\n\n```python name=i2 produces=file:b.png\nrun()\n```\n\n<!-- dankg:result name=i2 hash=0000000000000004 -->\n\n```\nok\n```\n");
        let mut tables = HashMap::new();
        tables.insert(0, ("csv".to_string(), "x\n1\n".to_string()));
        tables.insert(6, ("csv".to_string(), "x\n2\n".to_string()));
        let mut images = HashMap::new();
        images.insert(3, (Vec::new(), "a.png".to_string()));
        images.insert(9, (Vec::new(), "b.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (_, numbers) = figures(&d, &tables, &images, &mut diags);
        assert_eq!(numbers.get(&0), Some(&1), "first table");
        assert_eq!(numbers.get(&3), Some(&1), "first image, its own counter");
        assert_eq!(numbers.get(&6), Some(&2), "second table");
        assert_eq!(numbers.get(&9), Some(&2), "second image");
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    /// `weave=hidden` leaves no figure on the page, so it takes no number
    /// and never shifts the one after it.
    #[test]
    fn figures_never_numbers_a_hidden_figure() {
        let d = doc("```python name=a weave=hidden produces=file:a.png\nrun()\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\nok\n```\n\n```python name=b produces=file:b.png\nrun()\n```\n\n<!-- dankg:result name=b hash=0000000000000002 -->\n\n```\nok\n```\n");
        let mut images = HashMap::new();
        images.insert(0, (Vec::new(), "a.png".to_string()));
        images.insert(3, (Vec::new(), "b.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (labels, numbers) = figures(&d, &HashMap::new(), &images, &mut diags);
        assert_eq!(numbers.get(&0), None, "hidden, so not counted");
        assert_eq!(numbers.get(&3), Some(&1), "the visible one is still Figure 1");
        assert_eq!(labels.get(&0), Some(&"a".to_string()), "a hidden figure keeps its label");
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    /// `weave=output-hidden` drops the artifact half with the output
    /// (decision 53), so there is no figure left to count either.
    #[test]
    fn figures_never_numbers_an_output_hidden_figure() {
        let d = doc("```python name=a weave=output-hidden produces=file:a.png\nrun()\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\nok\n```\n");
        let mut images = HashMap::new();
        images.insert(0, (Vec::new(), "a.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (labels, numbers) = figures(&d, &HashMap::new(), &images, &mut diags);
        assert!(numbers.is_empty());
        assert_eq!(labels.get(&0), Some(&"a".to_string()));
    }

    /// `weave=source-hidden` keeps the artifact (decision 60), so its own
    /// figure renders and counts like any other.
    #[test]
    fn figures_numbers_a_source_hidden_figure() {
        let d = doc("```python name=a weave=source-hidden produces=file:a.png\nrun()\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\nok\n```\n");
        let mut images = HashMap::new();
        images.insert(0, (Vec::new(), "a.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (_, numbers) = figures(&d, &HashMap::new(), &images, &mut diags);
        assert_eq!(numbers.get(&0), Some(&1));
    }

    /// Numbering and labelling are separate. A figure whose label was
    /// dropped as a collision still renders, so it still counts.
    #[test]
    fn a_figure_whose_label_collided_is_still_numbered() {
        let d = doc("```python name=a label=chart produces=file:one.png\nrun()\n```\n\n<!-- dankg:result name=a hash=0000000000000001 -->\n\n```\nok\n```\n\n```python name=b label=chart produces=file:two.png\nrun()\n```\n\n<!-- dankg:result name=b hash=0000000000000002 -->\n\n```\nok\n```\n");
        let mut images = HashMap::new();
        images.insert(0, (Vec::new(), "one.png".to_string()));
        images.insert(3, (Vec::new(), "two.png".to_string()));
        let mut diags = Diags::new("t.md");
        let (labels, numbers) = figures(&d, &HashMap::new(), &images, &mut diags);
        assert_eq!(labels.get(&3), None, "the second label is dropped");
        assert_eq!(numbers.get(&3), Some(&2), "the figure itself still counts");
        assert_eq!(diags.items().len(), 1, "{:?}", diags.items());
    }

    fn one_image_figure(source: &str) -> (Document, HashMap<usize, (Vec<u8>, String)>) {
        (doc(source), [(0usize, (Vec::new(), "chart.png".to_string()))].into_iter().collect())
    }

    #[test]
    fn references_resolves_a_table_figure_to_both_backends_own_shapes() {
        let d = doc("```python name=t produces=file:a.csv\nrun()\n```\n\n<!-- dankg:result name=t hash=0000000000000001 -->\n\n```\nok\n```\n");
        let tables: HashMap<usize, (String, String)> = [(0, ("csv".to_string(), "x\n1\n".to_string()))].into_iter().collect();
        let labels = [(0usize, "t".to_string())].into_iter().collect();
        let numbers = [(0usize, 1u32)].into_iter().collect();
        let (typst, html) = references(&d, &tables, &labels, &numbers, &HashMap::new());
        assert_eq!(typst.get("t"), Some(&"fig:t".to_string()));
        assert_eq!(html.get("t"), Some(&("fig-t".to_string(), "Table 1".to_string())));
    }

    #[test]
    fn references_calls_an_image_figure_a_figure_not_a_table() {
        let (d, images) = one_image_figure("```python name=c produces=file:chart.png\nrun()\n```\n\n<!-- dankg:result name=c hash=0000000000000001 -->\n\n```\nok\n```\n");
        let _ = &images;
        let labels = [(0usize, "c".to_string())].into_iter().collect();
        let numbers = [(0usize, 2u32)].into_iter().collect();
        let (_, html) = references(&d, &HashMap::new(), &labels, &numbers, &HashMap::new());
        assert_eq!(html.get("c"), Some(&("fig-c".to_string(), "Figure 2".to_string())));
    }

    /// A heading resolves too (decision 64). HTML shows its own title
    /// rather than a number, since HTML numbers no heading (decision 68).
    #[test]
    fn references_resolves_a_heading_to_its_slug_and_its_title() {
        let d = doc("# The Design\n");
        let slugs = heading_slugs(&d);
        let (typst, html) = references(&d, &HashMap::new(), &HashMap::new(), &HashMap::new(), &slugs);
        assert_eq!(typst.get("the-design"), Some(&"sec:the-design".to_string()));
        assert_eq!(html.get("the-design"), Some(&("the-design".to_string(), "The Design".to_string())));
    }

    /// Declared beats derived: a figure label is written, a heading slug is
    /// computed from prose.
    #[test]
    fn a_figure_label_wins_a_clash_with_a_heading_slug() {
        let d = doc("# Chart\n\n```python name=chart produces=file:chart.png\nrun()\n```\n\n<!-- dankg:result name=chart hash=0000000000000001 -->\n\n```\nok\n```\n");
        let slugs = heading_slugs(&d);
        let labels = [(1usize, "chart".to_string())].into_iter().collect();
        let numbers = [(1usize, 1u32)].into_iter().collect();
        let (typst, _) = references(&d, &HashMap::new(), &labels, &numbers, &slugs);
        assert_eq!(typst.get("chart"), Some(&"fig:chart".to_string()));
    }

    #[test]
    fn a_hidden_figure_is_not_a_reference_target() {
        let labels = [(0usize, "c".to_string())].into_iter().collect();
        let d = doc("```python name=c weave=hidden produces=file:chart.png\nrun()\n```\n\n<!-- dankg:result name=c hash=0000000000000001 -->\n\n```\nok\n```\n");
        let (typst, html) = references(&d, &HashMap::new(), &labels, &HashMap::new(), &HashMap::new());
        assert!(typst.is_empty());
        assert!(html.is_empty());
    }

    #[test]
    fn resolve_references_passes_a_document_whose_references_all_resolve() {
        let d = doc("# Intro\n\nSee [[#intro]] and [the start](#intro).\n");
        let slugs = heading_slugs(&d);
        let (typst, _) = references(&d, &HashMap::new(), &HashMap::new(), &HashMap::new(), &slugs);
        let mut diags = Diags::new("t.md");
        assert_eq!(resolve_references(&d, &typst, &HashMap::new(), &HashMap::new(), &mut diags), 0);
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    /// One run reports every bad line, never just the first (decision 64).
    #[test]
    fn resolve_references_reports_every_unresolved_reference_in_one_walk() {
        let d = doc("# Intro\n\nSee [[#one]].\n\nAnd [[#two]] and [x](#three).\n");
        let slugs = heading_slugs(&d);
        let (typst, _) = references(&d, &HashMap::new(), &HashMap::new(), &HashMap::new(), &slugs);
        let mut diags = Diags::new("t.md");
        assert_eq!(resolve_references(&d, &typst, &HashMap::new(), &HashMap::new(), &mut diags), 3);
        assert_eq!(diags.count(crate::diag::Level::Error), 3, "{:?}", diags.items());
    }

    #[test]
    fn an_unresolved_reference_to_nothing_says_so() {
        let d = doc("Text [[#nope]].\n");
        let mut diags = Diags::new("t.md");
        resolve_references(&d, &HashMap::new(), &HashMap::new(), &HashMap::new(), &mut diags);
        assert!(diags.items()[0].message.contains("nothing in this document is named `nope`"), "{:?}", diags.items());
    }

    #[test]
    fn a_reference_to_a_named_block_that_is_no_figure_says_so() {
        let d = doc("```sh name=a\necho hi\n```\n\nText [[#a]].\n");
        let mut diags = Diags::new("t.md");
        resolve_references(&d, &HashMap::new(), &HashMap::new(), &HashMap::new(), &mut diags);
        assert!(diags.items()[0].message.contains("names a block, but not a figure"), "{:?}", diags.items());
    }

    #[test]
    fn a_reference_to_a_hidden_figure_names_the_attribute_that_hid_it() {
        let d = doc("```python name=c weave=hidden produces=file:chart.png\nrun()\n```\n\n<!-- dankg:result name=c hash=0000000000000001 -->\n\n```\nok\n```\n\nText [[#c]].\n");
        let labels = [(0usize, "c".to_string())].into_iter().collect();
        let mut diags = Diags::new("t.md");
        resolve_references(&d, &HashMap::new(), &labels, &HashMap::new(), &mut diags);
        assert!(diags.items()[0].message.contains("hidden by `weave=hidden`"), "{:?}", diags.items());
    }

    #[test]
    fn a_reference_to_an_output_hidden_figure_names_that_attribute_instead() {
        let d = doc("```python name=c weave=output-hidden produces=file:chart.png\nrun()\n```\n\n<!-- dankg:result name=c hash=0000000000000001 -->\n\n```\nok\n```\n\nText [[#c]].\n");
        let labels = [(0usize, "c".to_string())].into_iter().collect();
        let mut diags = Diags::new("t.md");
        resolve_references(&d, &HashMap::new(), &labels, &HashMap::new(), &mut diags);
        assert!(diags.items()[0].message.contains("hidden by `weave=output-hidden`"), "{:?}", diags.items());
    }

    /// Decision 41 is narrowed, not repealed: a wikilink naming another
    /// file is not a same-file fragment and is never resolved here.
    #[test]
    fn a_wikilink_naming_another_file_is_not_checked_at_all() {
        let d = doc("See [[Other]] and [[Other#chart]].\n");
        let mut diags = Diags::new("t.md");
        assert_eq!(resolve_references(&d, &HashMap::new(), &HashMap::new(), &HashMap::new(), &mut diags), 0);
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    /// A reference is legal inside emphasis, and inside a link's own text.
    #[test]
    fn a_reference_nested_in_emphasis_is_still_checked() {
        let d = doc("See *[[#nope]]* here.\n");
        let mut diags = Diags::new("t.md");
        assert_eq!(resolve_references(&d, &HashMap::new(), &HashMap::new(), &HashMap::new(), &mut diags), 1);
    }

    #[test]
    fn image_ext_recognizes_common_extensions_case_insensitively_and_canonicalizes_jpeg() {
        assert_eq!(image_ext("chart.png"), Some("png"));
        assert_eq!(image_ext("chart.PNG"), Some("png"));
        assert_eq!(image_ext("chart.jpg"), Some("jpg"));
        assert_eq!(image_ext("chart.jpeg"), Some("jpg"));
        assert_eq!(image_ext("chart.svg"), Some("svg"));
        assert_eq!(image_ext("data.csv"), None);
    }

    fn doc(source: &str) -> Document {
        Document::parse(source, &mut Diags::new("t.md"))
    }

    #[test]
    fn bibliography_is_none_when_neither_source_is_configured() {
        let d = doc("# H\n\n[@key]\n");
        let mut diags = Diags::new("t.md");
        assert!(bibliography(&d, "t.md", Path::new("."), &mut diags).is_none());
    }

    #[test]
    fn bibliography_from_a_hayagriva_fence_alone() {
        let d = doc("```hayagriva\nnetwok2019:\n  title: A Paper\n```\n\n[@netwok2019]\n");
        let mut diags = Diags::new("t.md");
        let bib = bibliography(&d, "t.md", Path::new("."), &mut diags).unwrap();
        assert!(bib.entries.contains_key("netwok2019"));
        assert_eq!(bib.order, vec!["netwok2019".to_string()]);
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    #[test]
    fn bibliography_from_a_frontmatter_file_alone() {
        let dir = scratch(&[
            ("refs.yml", "netwok2019:\n  title: A Paper\n"),
            ("a.md", "---\nbibliography: refs.yml\n---\n\n[@netwok2019]\n"),
        ]);
        let d = doc(&fs::read_to_string(dir.join("a.md")).unwrap());
        let mut diags = Diags::new("a.md");
        let bib = bibliography(&d, "a.md", &dir, &mut diags).unwrap();
        assert!(bib.entries.contains_key("netwok2019"));
        assert!(diags.is_empty(), "{:?}", diags.items());
    }

    #[test]
    fn bibliography_merges_both_sources_fence_wins_a_duplicate_key() {
        let dir = scratch(&[
            ("refs.yml", "a:\n  title: External\n"),
            ("doc.md", "---\nbibliography: refs.yml\n---\n\n```hayagriva\na:\n  title: Fence\n```\n\n[@a]\n"),
        ]);
        let d = doc(&fs::read_to_string(dir.join("doc.md")).unwrap());
        let mut diags = Diags::new("doc.md");
        let bib = bibliography(&d, "doc.md", &dir, &mut diags).unwrap();
        assert_eq!(bib.entries["a"].title.as_deref(), Some("Fence"));
        assert_eq!(diags.count(crate::diag::Level::Warn), 1);
    }

    #[test]
    fn citation_order_spans_headings_and_list_items() {
        let d = doc("```hayagriva\na:\n  title: A\nb:\n  title: B\n```\n\n## [@b]\n\n- [@a]\n");
        let mut diags = Diags::new("t.md");
        let bib = bibliography(&d, "t.md", Path::new("."), &mut diags).unwrap();
        assert_eq!(bib.order, vec!["b".to_string(), "a".to_string()]);
    }

    #[test]
    fn a_cited_key_absent_from_every_entry_warns() {
        let d = doc("```hayagriva\na:\n  title: A\n```\n\n[@missing]\n");
        let mut diags = Diags::new("t.md");
        let bib = bibliography(&d, "t.md", Path::new("."), &mut diags).unwrap();
        assert_eq!(diags.count(crate::diag::Level::Warn), 1);
        assert!(bib.order.contains(&"missing".to_string()));
    }

    #[test]
    fn an_uncited_entry_never_appears_in_the_ordered_list() {
        let d = doc("```hayagriva\na:\n  title: A\nb:\n  title: B\n```\n\n[@a]\n");
        let mut diags = Diags::new("t.md");
        let bib = bibliography(&d, "t.md", Path::new("."), &mut diags).unwrap();
        assert_eq!(bib.order, vec!["a".to_string()]);
        assert!(bib.entries.contains_key("b"));
    }

    #[test]
    fn a_second_hayagriva_fence_warns_and_is_ignored() {
        let d = doc("```hayagriva\na:\n  title: A\n```\n\n```hayagriva\nb:\n  title: B\n```\n\n[@a]\n");
        let mut diags = Diags::new("t.md");
        let bib = bibliography(&d, "t.md", Path::new("."), &mut diags).unwrap();
        assert!(bib.entries.contains_key("a"));
        assert!(!bib.entries.contains_key("b"));
        assert_eq!(diags.count(crate::diag::Level::Warn), 1);
    }

    #[test]
    fn render_pdf_writes_bibliography_yml_matching_the_merged_raw_text() {
        let dir = scratch(&[("a.md", "```hayagriva\na:\n  title: A\n```\n\n[@a]\n")]);
        run(dir.join("a.md").to_str().unwrap(), Format::Pdf, None, false, false).unwrap();
        let written = fs::read_to_string(dir.join(".dankg/build/weave/bibliography.yml")).unwrap();
        assert_eq!(written, "a:\n  title: A\n");
    }

    #[test]
    fn render_pdf_typ_emits_a_bibliography_call_and_a_real_citation() {
        let dir = scratch(&[("a.md", "```hayagriva\na:\n  title: A\n```\n\n[@a]\n")]);
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Pdf, None, false, false).unwrap();
        let typ = fs::read_to_string(report.typ_path.unwrap()).unwrap();
        assert!(typ.contains("#bibliography(\"bibliography.yml\")"), "{typ}");
        assert!(typ.contains("@a"), "{typ}");
    }

    #[test]
    fn render_pdf_with_no_bibliography_emits_no_bibliography_call() {
        let dir = scratch(&[("a.md", "# H\n\n[@a]\n")]);
        let report = run(dir.join("a.md").to_str().unwrap(), Format::Pdf, None, false, false).unwrap();
        let typ = fs::read_to_string(report.typ_path.unwrap()).unwrap();
        assert!(!typ.contains("#bibliography("), "{typ}");
        assert!(!dir.join(".dankg/build/weave/bibliography.yml").exists());
    }
}
