// generated by `dankg tangle` from src/data/bib.md -- do not edit

//! The Hayagriva schema layer on top of `data::yaml::YamlNode` -- decision
//! 58 (`plan-weave-citations.md`). `data::yaml` has no notion of what any
//! field name means; this module is the only place that does.
//!
//! Full Hayagriva fidelity: every field the format documents parses.
//! `author`/`editor` accept a bare scalar, a list of scalars, or a list
//! mixing structured mapping items; `parent` nests without a depth limit.
//!
//! A future field this module does not yet recognize still warns --
//! `KNOWN_FIELDS` is a reject list, not an allow list -- so a spec update
//! shows up as a diagnostic rather than silent data loss.

use super::yaml::YamlNode;
use crate::diag::Diags;

#[derive(Debug, Clone, PartialEq, Default)]
pub struct Person {
    /// The one required part of a person -- Hayagriva's own family name.
    pub name: String,
    pub given_name: Option<String>,
    pub prefix: Option<String>,
    pub suffix: Option<String>,
    pub alias: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Affiliated {
    pub person: Person,
    pub role: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum SerialNumber {
    Plain(String),
    Structured {
        doi: Option<String>,
        isbn: Option<String>,
        issn: Option<String>,
        pmid: Option<String>,
        pmcid: Option<String>,
        arxiv: Option<String>,
        serial: Option<String>,
    },
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct BibEntry {
    pub key: String,
    /// Hayagriva's own `type:` -- a free string, never a closed enum. A new
    /// entry type needs no code change here, because nothing branches on it.
    pub kind: Option<String>,
    pub title: Option<String>,
    pub authors: Vec<Person>,
    pub editors: Vec<Person>,
    /// Covers translator/director/illustrator/etc -- Hayagriva has no
    /// separate top-level field for any of those; each is an affiliated
    /// person with a `role`.
    pub affiliated: Vec<Affiliated>,
    pub date: Option<String>,
    pub publisher: Option<String>,
    pub location: Option<String>,
    pub organization: Option<String>,
    pub edition: Option<String>,
    pub genre: Option<String>,
    pub volume: Option<String>,
    pub volume_total: Option<String>,
    pub issue: Option<String>,
    pub chapter: Option<String>,
    pub page_range: Option<String>,
    pub page_total: Option<String>,
    pub time_range: Option<String>,
    pub runtime: Option<String>,
    pub serial_number: Option<SerialNumber>,
    pub url: Option<String>,
    pub url_date: Option<String>,
    pub archive: Option<String>,
    pub archive_location: Option<String>,
    pub call_number: Option<String>,
    pub language: Option<String>,
    pub note: Option<String>,
    /// `abstract` -- a reserved word in Rust, so the field is renamed.
    pub abstract_: Option<String>,
    /// Hayagriva's own `parent`: one entry or a list, unlimited nesting
    /// depth either way. An issue's own `parent` names its journal, and so
    /// on with no depth limit.
    pub parent: Vec<BibEntry>,
}

pub fn parse(text: &str, diags: &mut Diags) -> Vec<BibEntry> {
    let root = super::yaml::parse(text, diags);
    from_yaml(root, diags)
}

pub fn from_yaml(root: YamlNode, diags: &mut Diags) -> Vec<BibEntry> {
    let YamlNode::Map(entries) = root else {
        diags.warn(0, "a bibliography must be a mapping of citation keys to entries, ignored");
        return Vec::new();
    };
    entries
        .into_iter()
        .filter_map(|(key, value)| match value {
            YamlNode::Map(fields) => Some(bib_entry_from_fields(&fields, key, diags)),
            _ => {
                diags.warn(0, format!("bibliography entry `{key}` is not a mapping, ignored"));
                None
            }
        })
        .collect()
}

const KNOWN_FIELDS: &[&str] = &[
    "type",
    "title",
    "author",
    "editor",
    "affiliated",
    "date",
    "publisher",
    "location",
    "organization",
    "edition",
    "genre",
    "volume",
    "volume-total",
    "issue",
    "chapter",
    "page-range",
    "page-total",
    "time-range",
    "runtime",
    "serial-number",
    "url",
    "archive",
    "archive-location",
    "call-number",
    "language",
    "note",
    "abstract",
    "parent",
];

fn bib_entry_from_fields(fields: &[(String, YamlNode)], key: String, diags: &mut Diags) -> BibEntry {
    let (url, url_date) = match find(fields, "url") {
        Some(YamlNode::Scalar(s)) => (Some(s.clone()).filter(|s| !s.is_empty()), None),
        Some(YamlNode::Map(uf)) => (find(uf, "value").and_then(scalar_string), find(uf, "date").and_then(scalar_string)),
        _ => (None, None),
    };

    for (k, _) in fields {
        if !KNOWN_FIELDS.contains(&k.as_str()) {
            diags.warn(0, format!("unrecognized bibliography field `{k}`, ignored"));
        }
    }

    BibEntry {
        key,
        kind: find(fields, "type").and_then(scalar_string),
        title: find(fields, "title").and_then(scalar_string),
        authors: find(fields, "author").map(persons_from).unwrap_or_default(),
        editors: find(fields, "editor").map(persons_from).unwrap_or_default(),
        affiliated: find(fields, "affiliated").map(affiliated_from).unwrap_or_default(),
        date: find(fields, "date").and_then(scalar_string),
        publisher: find(fields, "publisher").and_then(scalar_string),
        location: find(fields, "location").and_then(scalar_string),
        organization: find(fields, "organization").and_then(scalar_string),
        edition: find(fields, "edition").and_then(scalar_string),
        genre: find(fields, "genre").and_then(scalar_string),
        volume: find(fields, "volume").and_then(scalar_string),
        volume_total: find(fields, "volume-total").and_then(scalar_string),
        issue: find(fields, "issue").and_then(scalar_string),
        chapter: find(fields, "chapter").and_then(scalar_string),
        page_range: find(fields, "page-range").and_then(scalar_string),
        page_total: find(fields, "page-total").and_then(scalar_string),
        time_range: find(fields, "time-range").and_then(scalar_string),
        runtime: find(fields, "runtime").and_then(scalar_string),
        serial_number: find(fields, "serial-number").and_then(serial_number_from),
        url,
        url_date,
        archive: find(fields, "archive").and_then(scalar_string),
        archive_location: find(fields, "archive-location").and_then(scalar_string),
        call_number: find(fields, "call-number").and_then(scalar_string),
        language: find(fields, "language").and_then(scalar_string),
        note: find(fields, "note").and_then(scalar_string),
        abstract_: find(fields, "abstract").and_then(scalar_string),
        parent: find(fields, "parent").map(|n| parent_from(n, diags)).unwrap_or_default(),
    }
}

fn find<'a>(fields: &'a [(String, YamlNode)], key: &str) -> Option<&'a YamlNode> {
    fields.iter().find(|(k, _)| k == key).map(|(_, v)| v)
}

fn scalar_string(node: &YamlNode) -> Option<String> {
    match node {
        YamlNode::Scalar(s) if !s.is_empty() => Some(s.clone()),
        _ => None,
    }
}

/// Hayagriva's own single-or-list convention: a lone node is a list of one.
fn as_list(node: &YamlNode) -> Vec<&YamlNode> {
    match node {
        YamlNode::Seq(items) => items.iter().collect(),
        other => vec![other],
    }
}

fn parent_from(node: &YamlNode, diags: &mut Diags) -> Vec<BibEntry> {
    as_list(node)
        .into_iter()
        .filter_map(|item| match item {
            YamlNode::Map(fields) => Some(bib_entry_from_fields(fields, String::new(), diags)),
            _ => None,
        })
        .collect()
}

fn persons_from(node: &YamlNode) -> Vec<Person> {
    as_list(node).into_iter().filter_map(person_from).collect()
}

fn person_from(node: &YamlNode) -> Option<Person> {
    match node {
        YamlNode::Scalar(s) if !s.is_empty() => Some(person_from_scalar(s)),
        YamlNode::Map(fields) => Some(Person {
            name: find(fields, "name").and_then(scalar_string).unwrap_or_default(),
            given_name: find(fields, "given-name").and_then(scalar_string),
            prefix: find(fields, "prefix").and_then(scalar_string),
            suffix: find(fields, "suffix").and_then(scalar_string),
            alias: find(fields, "alias").and_then(scalar_string),
        }),
        _ => None,
    }
}

fn person_from_scalar(s: &str) -> Person {
    let parts: Vec<&str> = s.split(',').map(str::trim).collect();
    let name = parts[0].to_string();
    match parts.len() {
        1 => Person { name, ..Person::default() },
        2 => Person { name, given_name: Some(parts[1].to_string()), ..Person::default() },
        _ => Person {
            name,
            suffix: Some(parts[1].to_string()),
            given_name: Some(parts[2..].join(", ")),
            ..Person::default()
        },
    }
}

fn affiliated_from(node: &YamlNode) -> Vec<Affiliated> {
    as_list(node)
        .into_iter()
        .flat_map(|item| {
            let YamlNode::Map(fields) = item else { return Vec::new() };
            let role = find(fields, "role").and_then(scalar_string);
            let names = find(fields, "names").map(persons_from).unwrap_or_default();
            names.into_iter().map(move |person| Affiliated { person, role: role.clone() }).collect::<Vec<_>>()
        })
        .collect()
}

fn serial_number_from(node: &YamlNode) -> Option<SerialNumber> {
    match node {
        YamlNode::Scalar(s) => Some(SerialNumber::Plain(s.clone())),
        YamlNode::Map(fields) => Some(SerialNumber::Structured {
            doi: find(fields, "doi").and_then(scalar_string),
            isbn: find(fields, "isbn").and_then(scalar_string),
            issn: find(fields, "issn").and_then(scalar_string),
            pmid: find(fields, "pmid").and_then(scalar_string),
            pmcid: find(fields, "pmcid").and_then(scalar_string),
            arxiv: find(fields, "arxiv").and_then(scalar_string),
            serial: find(fields, "serial").and_then(scalar_string),
        }),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse_ok(text: &str) -> (Vec<BibEntry>, Diags) {
        let mut diags = Diags::new("t.yml");
        let entries = parse(text, &mut diags);
        (entries, diags)
    }

    #[test]
    fn a_minimal_single_field_entry() {
        let (entries, diags) = parse_ok("netwok2019:\n  title: A Paper\n");
        assert!(diags.is_empty(), "{:?}", diags.items());
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].key, "netwok2019");
        assert_eq!(entries[0].title.as_deref(), Some("A Paper"));
    }

    #[test]
    fn author_as_a_bare_scalar_is_one_person() {
        let (entries, _) = parse_ok("a:\n  author: Smith, John\n");
        assert_eq!(entries[0].authors, vec![Person { name: "Smith".into(), given_name: Some("John".into()), ..Person::default() }]);
    }

    #[test]
    fn author_as_a_list_mixing_scalar_and_structured_items() {
        let (entries, _) = parse_ok("a:\n  author:\n    - Smith, John\n    - name: Doe\n      given-name: Jane\n      alias: JD\n");
        assert_eq!(
            entries[0].authors,
            vec![
                Person { name: "Smith".into(), given_name: Some("John".into()), ..Person::default() },
                Person { name: "Doe".into(), given_name: Some("Jane".into()), alias: Some("JD".into()), ..Person::default() },
            ]
        );
    }

    #[test]
    fn a_scalar_person_with_the_suffix_segment() {
        let (entries, _) = parse_ok("a:\n  author: King, Jr., Martin Luther\n");
        assert_eq!(
            entries[0].authors,
            vec![Person {
                name: "King".into(),
                suffix: Some("Jr.".into()),
                given_name: Some("Martin Luther".into()),
                ..Person::default()
            }]
        );
    }

    #[test]
    fn an_editor_list() {
        let (entries, _) = parse_ok("a:\n  editor:\n    - Ed, One\n    - Ed, Two\n");
        assert_eq!(entries[0].editors.len(), 2);
        assert_eq!(entries[0].editors[0].name, "Ed");
    }

    #[test]
    fn affiliated_with_two_different_roles() {
        let (entries, diags) = parse_ok(
            "a:\n  affiliated:\n    - role: translator\n      names: Trans, Lee\n    - role: director\n      names: Dir, Sam\n",
        );
        assert!(diags.is_empty(), "{:?}", diags.items());
        assert_eq!(
            entries[0].affiliated,
            vec![
                Affiliated { person: Person { name: "Trans".into(), given_name: Some("Lee".into()), ..Person::default() }, role: Some("translator".into()) },
                Affiliated { person: Person { name: "Dir".into(), given_name: Some("Sam".into()), ..Person::default() }, role: Some("director".into()) },
            ]
        );
    }

    #[test]
    fn serial_number_as_a_plain_string() {
        let (entries, _) = parse_ok("a:\n  serial-number: SN-1\n");
        assert_eq!(entries[0].serial_number, Some(SerialNumber::Plain("SN-1".into())));
    }

    #[test]
    fn serial_number_as_a_structured_map() {
        let (entries, _) = parse_ok("a:\n  serial-number:\n    doi: 10.1/x\n    isbn: 123\n");
        assert_eq!(
            entries[0].serial_number,
            Some(SerialNumber::Structured {
                doi: Some("10.1/x".into()),
                isbn: Some("123".into()),
                issn: None,
                pmid: None,
                pmcid: None,
                arxiv: None,
                serial: None,
            })
        );
    }

    #[test]
    fn a_url_with_an_access_date() {
        let (entries, _) = parse_ok("a:\n  url:\n    value: https://x\n    date: 2020-01-01\n");
        assert_eq!(entries[0].url.as_deref(), Some("https://x"));
        assert_eq!(entries[0].url_date.as_deref(), Some("2020-01-01"));
    }

    #[test]
    fn a_bare_url_has_no_access_date() {
        let (entries, _) = parse_ok("a:\n  url: https://x\n");
        assert_eq!(entries[0].url.as_deref(), Some("https://x"));
        assert_eq!(entries[0].url_date, None);
    }

    #[test]
    fn parent_as_a_two_level_chain() {
        let (entries, diags) = parse_ok("a:\n  title: Article\n  parent:\n    title: Issue\n    parent:\n      title: Journal\n");
        assert!(diags.is_empty(), "{:?}", diags.items());
        let issue = &entries[0].parent[0];
        assert_eq!(issue.title.as_deref(), Some("Issue"));
        assert_eq!(issue.parent[0].title.as_deref(), Some("Journal"));
    }

    #[test]
    fn parent_as_a_list_of_two_entries() {
        let (entries, _) = parse_ok("a:\n  parent:\n    - title: P1\n    - title: P2\n");
        assert_eq!(entries[0].parent.len(), 2);
        assert_eq!(entries[0].parent[1].title.as_deref(), Some("P2"));
    }

    #[test]
    fn every_remaining_scalar_field_round_trips() {
        let text = "a:\n  edition: 2nd\n  genre: novel\n  location: Paris\n  organization: ACM\n  page-total: 300\n  volume-total: 3\n  chapter: 4\n  time-range: 1-2\n  runtime: 90min\n  archive: LOCKSS\n  archive-location: box-1\n  call-number: QA1\n  language: en\n  note: a note\n  abstract: an abstract\n";
        let (entries, diags) = parse_ok(text);
        assert!(diags.is_empty(), "{:?}", diags.items());
        let e = &entries[0];
        assert_eq!(e.edition.as_deref(), Some("2nd"));
        assert_eq!(e.genre.as_deref(), Some("novel"));
        assert_eq!(e.location.as_deref(), Some("Paris"));
        assert_eq!(e.organization.as_deref(), Some("ACM"));
        assert_eq!(e.page_total.as_deref(), Some("300"));
        assert_eq!(e.volume_total.as_deref(), Some("3"));
        assert_eq!(e.chapter.as_deref(), Some("4"));
        assert_eq!(e.time_range.as_deref(), Some("1-2"));
        assert_eq!(e.runtime.as_deref(), Some("90min"));
        assert_eq!(e.archive.as_deref(), Some("LOCKSS"));
        assert_eq!(e.archive_location.as_deref(), Some("box-1"));
        assert_eq!(e.call_number.as_deref(), Some("QA1"));
        assert_eq!(e.language.as_deref(), Some("en"));
        assert_eq!(e.note.as_deref(), Some("a note"));
        assert_eq!(e.abstract_.as_deref(), Some("an abstract"));
    }

    #[test]
    fn duplicate_top_level_citation_key_warns_and_last_wins() {
        let (entries, diags) = parse_ok("a:\n  title: First\na:\n  title: Second\n");
        assert_eq!(diags.count(crate::diag::Level::Warn), 1);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].title.as_deref(), Some("Second"));
    }

    #[test]
    fn an_unrecognized_field_warns_and_is_ignored() {
        let (entries, diags) = parse_ok("a:\n  title: T\n  not-a-real-field: x\n");
        assert_eq!(diags.count(crate::diag::Level::Warn), 1);
        assert_eq!(entries[0].title.as_deref(), Some("T"));
    }

    #[test]
    fn a_non_mapping_entry_warns_and_is_dropped() {
        let (entries, diags) = parse_ok("a: just a string\nb:\n  title: T\n");
        assert_eq!(diags.count(crate::diag::Level::Warn), 1);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].key, "b");
    }

    #[test]
    fn kind_is_a_free_string_not_a_closed_enum() {
        let (entries, _) = parse_ok("a:\n  type: some-future-entry-type-not-yet-invented\n");
        assert_eq!(entries[0].kind.as_deref(), Some("some-future-entry-type-not-yet-invented"));
    }
}
